### ISSUE TITLE
Obtain npm ownership of prettier-plugin-java

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#102]
>$ npm owner ls prettier-plugin-java
thorbenvh8 <thorben@...>

**Comment by jdubois** [comment]
Thanks @bd82 and yes I need to ask @thorbenvh8 for this (but since today I know how this works!)

**Comment by bd82** [comment]
Reminder ⏰ 
😄

**Comment by jdubois** [comment]
Thanks @bd82 - I just sent a message to @thorbenvh8 !

**Comment by jdubois** [comment]
This should be OK!
Thanks a lot @thorbenvh8  !
And @bd82 you should have the publish rights as you are part of the "prettier" team in the "jhispter" org, so you can test whenever you want (anyway you could do beta releases at some point)

**Comment by bd82** [comment]
Thanks it looks good.

I would probably release the parser package as a beta in the near future, but right now
there is no prettier-java package in the repo yet 😄  as I still need to evaluate if/how to re-write it.
