### ISSUE TITLE
Align implementation of whitespace Token with the Spec

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#105]
https://github.com/jhipster/prettier-java/blob/5ef66ae309b41e6634d6e027631c824482d4af96/packages/java-parser/src/tokens.js#L108-L109

"\s" regexp in JavaScript has a very specific meaning.
>  Matches a single white space character, including space, tab, form feed, line feed and other Unicode spaces. Equivalent to [ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff].      For example, /\s\w*/ matches " bar" in "foo bar".

But that may not be equivalent to the definition of **Java** whitespace.

**Comment by bd82** [comment]
See the offical definition in the Java Specifications.
https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.

**Comment by Hawkurane** [comment]
Hello, I've submitted a pull request (#145) to redefine the whitespace definition after adding a few more sample repos to parse (mainly sample JHipster apps and spring framework to make sure it can run at least through them).

**Comment by bd82** [comment]
Hi @Hawkurane and thanks 😄 

I reviewed #145 See comments there

**Comment by clement26695** [comment]
Close this as it is resolved in #146 (correct me if I'm wrong)
