### ISSUE TITLE
Architecture: Evaluate parser re-write

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#108]
The existing parser is nearly complete, however I have some concerns regarding it.

## Alignment to the spec
The main concern is that it does seem not follow the [official specification](https://docs.oracle.com/javase/specs/jls/se11/html/jls-19.html) as **literally** as possible.
- Nor does it document where deviations from the spec have occurred.

That is not to mean that the language the parser accepts is not equivalent to the language the specifications define, rather that the style / structure of the parser and the spec are different.

### Implications
The problem is that this mis-alignment:
- Makes it difficult to reach a high confidence that the parser perfectly aligns with the spec.
  * AFAIK The problem of determining if two context free grammars are equivalent is **undecidable**.
- Makes it more difficult to update the parser to future spec versions.

This will **increases the TCO** of the parser module and the whole project.

## Secondary Issues
I'm not 100% certain regarding these issues yet.
- I'd like to evaluate alternatives to creating an AST for printing #107. 
- Parser performance seems a little low.
- I'd like to evaluate alternatives to the handling of empty comments and other special whitespace sensitive TokenTypes.
- I'd like to evaluate alternatives to the comment attaching (on CST) logic.

## What this all means
The combination of all these issues means I'm evaluating a **major refactor/re-write** of the project.
My plan is as follows:
- [ ] Rewrite the parser to align to the spec.
   - Goal/milestone: Parse a few million lines of Java Code without errors.
- [ ] Add custom logic to augment the CST with information needed for prettier scenario:
      * e.g: attach comments.
- [ ] Evaluate writing a printer as a visitor on the CST.

That is a quite **a lot of work**...
I am fairy confidant on my ability to implement a high quality Java Parser, and am semi confidant I will have the time to do so 😄 
And have already started working on the re-write in a separate branch: https://github.com/jhipster/prettier-java/commit/eeb49e5d4bea809a852ec52c79538e57 

I am a lot less certain regarding the other topics, it i possible my involvement will end with just re-writing the parser, although I do hope to at least provide a simple infrastructure to enable the community to
complete the printer...

As this is a spare time side project I can't really make any hard commitments.
I guess I will keep this thread up to date with my progress and we will evaluate the status in a couple of weeks...

**Comment by deepu105** [comment]
I think that's what matters the most. Given your expertise, setting up the
best starting point means we can release a higher quality initial version
and hope that the community will continue the efforts. We announced this on
Devoxx and reaction was quite positive

**Comment by jdubois** [comment]
Yes I fully agree with @deepu105 - @bd82 you're the best here, and the most important thing from a JHipster perspective is to help people get on board as easy as possible. That's how we got nearly 500 contributors, and it's thanks to them that the project is a success.

**Comment by bd82** [comment]
## Status Update:
I think the **first draft** of the parser rewrite (in #109) is getting close to **50% done**.
- Not sure how much effort will be needed to get the first draft actually working 😄 

I seem to be able to achieve the design objective of aligning very strongly with the official spec 
by carefully using **optimized backtracking**:
>Recursive descent with backtracking is a technique that determines which production to use by trying each production in turn. Recursive descent with backtracking is not limited to LL(k) grammars, but is not guaranteed to terminate unless the grammar is LL(k). Even when they terminate, parsers that use recursive descent with backtracking may require exponential time.

Would be interesting to see the performance characteristics of the end result, but I do not think
There would be any performance problem for prettier scenarios.

**Comment by bd82** [comment]
## Status Update:

The initial version of the parser re-write was merged to master.
Work will continue on the master branch

The results are:
- ~80% alignment with the official spec.
- Reduced Lexer code size to about a third of the original size.
- Performance of the new parser is a bit slow (1/3 of the previous parser).
  This is still good enough for the prettier scenario, however performance optimizations would need to be investigated.

The next steps are:
1. Bug fixes in the new Parser to get more source code samples working.
2. Documentation. 
3. Performance investigation.

And than attempt to create a **re-writer** that works on the CST (#107)
