### ISSUE TITLE
Lexer Gaps

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#112]
- [x] Whitespace definition (#105)
- [x] Negative numbers (#103 )
- [x] Unicode Identifiers
- [ ] Special lexing rules for "requires" and "transitive" keywords
      - https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.9

**Comment by pascalgrimaud** [comment]
Adding a bounty on this

**Comment by bd82** [comment]
I could have a look at this on the weekend, should I assign myself to it?

**Comment by clement26695** [comment]
Yes, go ahead ! 😄

**Comment by clementdessoude** [comment]
Just a reminder: do not forget to claim your bounty @bd82, you deserve it :)

**Comment by bd82** [comment]
Thanks :)

**Comment by bd82** [comment]
All these forms are too complicated for me additionally paypal annoyed me so I closed my account there 😄 .

You can use this 100$ for some other bounty...
