### ISSUE TITLE
Parser Gaps

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#113]
- [x] Bit shifting operators must **not** include whitespace
       https://github.com/jhipster/prettier-java/blob/5ef66ae309b41e6634d6e027631c824482d4af96/packages/java-parser/src/productions/expressions.js#L150-L156
- [ ] Some optimized backtracking logic do not provide location information on error, e.g:
      https://github.com/jhipster/prettier-java/blob/5ef66ae309b41e6634d6e027631c824482d4af96/packages/java-parser/src/productions/classes.js#L784-L787
- [x] Some matches vs Identifiers do not take token categories into account, the chevrotain.tokenMatcher must be used instead., e.g: https://github.com/jhipster/prettier-java/blob/5ef66ae309b41e6634d6e027631c824482d4af96/packages/java-parser/src/productions/classes.js#L731
- [ ] Need farther investigation on reducing the use of backtracking.
- [ ] The var keyword is only allowed to be used as an Identifier in certain contexts and disallowed in others, this is currently not implemented by the parser.
  - e.g: https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-TypeIdentifier
- [x] Attaching Comments to the CST (#117)

**Comment by pascalgrimaud** [comment]
Adding a bounty on this

**Comment by bd82** [comment]
Not sure this is suitable for a bounty, it is more like a list of issues...

**Comment by pascalgrimaud** [comment]
Ok, just tell me where I can reassign the bounty

**Comment by bd82** [comment]
>  The var keyword is only allowed to be used as an Identifier in certain contexts and disallowed in others, this is currently not implemented by the parser.
e.g: docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-TypeIdentifier

This may be a single issue. Which may be important enough for bounty as it touches on correctness.

> Some optimized backtracking logic do not provide location information on error, e.g:

This is a separate issue, which is not specific enough as it does not specify the list
of such errors that is expected to include location information. It may be less important as it deals with performance and simplification.

> Need farther investigation on reducing the use of backtracking.

This is another separate issue and it may be completely "theoretical" So I am not sure it is suitable for bounty.

**Comment by clement26695** [comment]
I agree. We should write another issue for the var/TypeIdentifier issue. It is not prioritary for the moment as it does not cause any bug, but it should be dealt with at some point
