### ISSUE TITLE
Parser Benchmark

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#118]
The parse-samples script is used as a form of benchmark.
However a better benchmark could include comparison to other Parsers
(e.g Antlr4 Java  grammar / Original java-parser package based on peg.js)

Such a benchmark should also be implemented using benchmark.js 
instead of just "new Date.getTime()" counters.

**Comment by Shaolans** [comment]
Hi @bd82,
The benchmark should bench only a file or rather on an entire repository ?
About the parsers, we then have to choose parsers that already have a grammar for the Java language (I think Antlr4 have one for Java 9). By the way, how can I retrieve the original java-parser ?

**Comment by bd82** [comment]
> how can I retrieve the original java-parser ?

Access old versions of the relevant npm package.
- https://www.npmjs.com/package/java-parser

> The benchmark should bench only a file or rather on an entire repository ?

We don't want the benchmark to be too slow, nor do we want it to be too shallow
Maybe a small repo with a ~10,000 LOC at least?

Also note that sometimes some parsers can only handle very small inputs.
I've had this case when I benchmarked some JavaScript parsers generated from parsing libraries.
So I could only do a comparison benchmark using a tiny 100 lines source code input 😄 

Maybe we also need a benchmark to compare the latest released version of our java-parser
and the new upcoming version. see example here: https://github.com/bd82/regexp-to-ast/tree/master/benchmark

**Comment by Shaolans** [comment]
Hi, I started to make a parser benchmark [here](https://github.com/Shaolans/prettier-java/tree/benchmark).
I am currently only comparing the original parser vs the new one (it is incredibly fast !)
```
Java parser benchmark
Original Java Parser x 7.55 ops/sec ±4.05% (24 runs sampled)
Prettier-Java x 573 ops/sec ±2.60% (84 runs sampled)
Fastest is Prettier-Java
```

> Also note that sometimes some parsers can only handle very small inputs.
> I've had this case when I benchmarked some JavaScript parsers generated from parsing libraries.
> So I could only do a comparison benchmark using a tiny 100 lines source code input smile

I am experiencing the same issue here, I added ANTLR4 but I had to remove it, looks like performance-wise, it does not look really good with JavaScript... I tried to parse a file of 10 LOC and it took about 2 minutes to complete and it seems I am not the only one that have the [issue](https://stackoverflow.com/questions/38571162/antlr4-javascript-target-very-slow).

I am currently launching the benchmark on a Java file of ~100 LOC, and it takes about 14 seconds to complete the bench. On a folder of 20 files (total 1580 LOC), it takes 2 minutes to completes.
It seems to take quite some times... I don't know if I missed something ?

**Comment by bd82** [comment]
>  I am currently only comparing the original parser vs the new one (it is incredibly fast !)

It is more that the old one is incredibly slow 😄.
The speed is not amazing relative to other Chevrotain Parsers because of the very complex grammar
with all the backtracking, see #106 #115 

> I am currently launching the benchmark on a Java file of ~100 LOC, and it takes about 14 seconds to complete the bench. On a folder of 20 files (total 1580 LOC), it takes 2 minutes to completes.
It seems to take quite some times... I don't know if I missed something ?

Maybe there is a-lot of variance in the numbers and benchmark.js does many samples
until it has a high confidence in the results?

**Comment by Shaolans** [comment]
> It is more that the old one is incredibly slow smile.
> The speed is not amazing relative to other Chevrotain Parsers because of the very complex grammar
> with all the backtracking, see #106 #115

When you run this [bench](https://sap.github.io/chevrotain/performance/), this is still quite impressive !

> Maybe there is a-lot of variance in the numbers and benchmark.js does many samples
> until it has a high confidence in the results?

Well, for the file I was talking about earlier the original parser run 24 times and prettier-java 84 times.
But the culprit is the original parser, it takes quite a long time to parse the file (still faster than ANTLR4 though).
I ran the benchmark on the jhipster repository (6-7k LOC) and it takes me 10 minutes to finish the execution...
Here is the result.
```
Java parser benchmark
Prettier-Java x 6.07 ops/sec ±2.30% (20 runs sampled)
Original Java Parser x 0.02 ops/sec ±0.31% (5 runs sampled)
Fastest is Prettier-Java
```
What should we do ? Reduce the number of files ?

**Comment by bd82** [comment]
> When you run this bench, this is still quite impressive !

😄 an hand crafted and optimized parser such as Acorn could still be x2-x3 faster.
But such is the price of abstraction and features, and more most scenario
one does not actually need to parse at many hundred of thousands of LOC. per second.

> What should we do ? Reduce the number of files ?

Have a one comparative benchmark with a small input size so the other parsers can terminate in reasonable time. and one **another** benchmark which we will use to compare java-parser "master"
to it's previous version which would have a larger input size.
Aim for less than one minute benchmark time in both.

One is for Public Relations / Demo purposes.
The other is a tool for us to evaluate performance optimizations and regressions over time.
