### ISSUE TITLE
Cold Start Performance

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#119]
The Java Grammar is quite complex and Chevrotain performs many checks and analysis during
the initial Parser initialization.

The end result is that it takes > 100ms on a fast modern CPU to startup the parser.
Now this is not the worst thing in the world for a prettier-scenario, but it still warrants optimization.

The first thing that can be done is implement serialization and de-serialization of the grammar internal structure and inspect what potential performance benefits that can be gained.
- See: https://github.com/SAP/chevrotain/tree/master/examples/parser/serialized_grammar
- The complexity with this is to ensure the serialized artifacts are always up-todate
  and to provide a dev-mode where no serialized artifacts are needed to avoid slowing down the fast feedback cycles (which JavaScript excels in).

Additional options would be to investigate if anymore of the checks and analysis done during the Parser constructor can be avoided in productive flows, in other words the ability to have an even more **minimal startup** than just de-serializing a grammar.
- This could be more complex as it requires diving into Chevrotain internals.
- If this is possible it may lead to a Chevrotain generic feature that implement it.

The last possible optimization would be to actually pre-generate the lookahead functions
instead of creating them on the fly, But that is much farther into the future and outside the scope of prettier-java.

**Comment by bd82** [comment]
The "Help Wanted" label refers mainly to trying to implement [grammar serialization](https://github.com/SAP/chevrotain/tree/master/examples/parser/serialized_grammar)
This is an existing and documented Chevrotain feature so knowledge of the internals is not needed.

**Comment by Hawkurane** [comment]
I've tried to implement the grammar serialization and it seems using a custom token matcher (for java identifier) makes the pattern void (such as [this](https://github.com/Hawkurane/prettier-java/blob/2a9e12377fd098669ebb7a3aa5719bdc7420f5a9/packages/java-parser/src/gen/grammar.json#L2932)). This makes an issue when we are loading the grammar.json : the parser can't parse the identifiers anymore :cry:

**Comment by bd82** [comment]
Interesting, this is strange because the Tokens themselves are not serialized, I will look into this

**Comment by Hawkurane** [comment]
It seems by removing this "[exec](https://github.com/jhipster/prettier-java/pull/194/files#diff-9895c9bb38d5d2fd1045156f0b581ce8R81)" attribute in object and passing directly the function name to tokenize identifiers seems to do the trick. But I don't understand how are the custom token matcher patterns/functions described in the parser. It seems to map it to an idx but I am unsure of what it does specifically.

**Comment by bd82** [comment]
Interesting maybe something does "toString" on the pattern property and if its a function and not an object with "exec" than the "toString" returns something useful and that is used as a key in the de-serialzie.

**Comment by Hawkurane** [comment]
Closed issue, see [#194](https://github.com/jhipster/prettier-java/pull/194) for more information.
