### ISSUE TITLE
Ensure master branch is protected

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#121]
@jdubois can you please ensure the master branch is protected so it cannot be force pushed.
I do not have permissions for that...

Note that advanced features of requiring status checks of PRs are not needed.
Just the most basic protection.

Thanks. 😄

**Comment by jdubois** [comment]
Thanks @bd82 - I didn't know this could be done, and we probably also need this for the other JHipster projects.

Can you check this looks OK to you:

![screenshot 2019-01-11 17 57 23](https://user-images.githubusercontent.com/316835/51048113-714d9e00-15ca-11e9-84e5-8a7135818a3c.png)

**Comment by bd82** [comment]
Thanks @jdubois 
I tested and it works perfectly:

> remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to a protected branch
To https://github.com/jhipster/prettier-java.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jhipster/prettier-java.git'

>  I didn't know this could be done, and we probably also need this for the other JHipster projects.

It is a very important option to enable.
Somebody could inadvertently delete large amounts of history.
- Actually happened in one of my projects one 😄

**Comment by jdubois** [comment]
Thanks, I will do the same on the other projects!
