### ISSUE TITLE
Can't parse explicit generic invocation: this.<Bar>baz()

### ISSUE THREAD

**Issue by FauxFaux** [jhipster/prettier-java#129]
We see this syntax used in the Guava tests:

```java
    try {
      map.getInstance(this.<Number>anyIterableType());
      fail();
    } catch (IllegalArgumentException expected) {
```

https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/guava-tests/test/com/google/common/reflect/MutableTypeToInstanceMapTest.java#L211-L214

**Comment by bd82** [comment]
Thanks for reporting this 👍
