### ISSUE TITLE
Can't parse scientific notation: 1.0e-10

### ISSUE THREAD

**Issue by FauxFaux** [jhipster/prettier-java#131]
I believe this is trying to parse `1.0e-2`.

Seen in Guava:

https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/guava-tests/test/com/google/common/math/DoubleMathTest.java#L715

**Comment by bd82** [comment]
Thanks for reporting this.

Looks like that expression is being tokenized as four seprate tokens.
> ['1.00', 'e', '-', '2']

**Comment by bd82** [comment]
I am a bit constrained on time at the moment and trying to investigate a prettier plugin scenario
in a smaller scope (Toml - https://github.com/bd82/toml-tools)

Part of the intent is that such a small prettier plugin could provide an E2E template / guidelines
For [JHipster trainees that will hopefully join this project](https://groups.google.com/d/msg/jhipster-dev/VMQWbB9lbs0/1sfSFyR_DgAJ).

But this is likely a small issue and if you want to try tackling it I will find the time to provide assistance...
