### ISSUE TITLE
Can't parse cast in: WildcardType toWildcardType = (WildcardType) to;

### ISSUE THREAD

**Issue by clement26695** [jhipster/prettier-java#138]
Found in https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/guava/src/com/google/common/reflect/TypeResolver.java#L141

It seems that the parser can not parse the casting operation here.
```java
WildcardType toWildcardType = (WildcardType) to;
```

The same situation seems to appear in : https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/guava/src/com/google/common/io/CharStreams.java#L76

**Comment by bd82** [comment]
Also note we are using "optimized manual backtracking" for identifying a cast expression.
- https://github.com/jhipster/prettier-java/blob/master/packages/java-parser/src/productions/expressions.js#L200-L203

So the problem is probably in that logic

**Comment by clement26695** [comment]
I understood why the parser failed : it is because of the use of the restricted keyword **to**. 

Just adding in the **isReferenceTypeCastExpression** rule a test to return true if the next token is a restricted keyword could work but there is probably something that need to be fixed elsewhere (in the unaryExpressionNotPlusMinus maybe ?)

**Comment by bd82** [comment]
RestrictedKeyword can already be used as an Identifier (Token Categories).
- https://github.com/jhipster/prettier-java/blob/master/packages/java-parser/src/tokens.js#L179

But the check in the optimized backtracking lookahead
- https://github.com/jhipster/prettier-java/blob/88caf362d34d7e02ad43b83a8448ac696cb7fcdd/packages/java-parser/src/productions/expressions.js#L621

Does not use the **tokenMatcher** utility and thus does not respect the token categories.

I think we need to adjust **all** token matching to use **tokenMatcher** and **never** compare the tokenType directly using "==="

**Comment by bd82** [comment]
Note the restricted keywords have some special behavior that is not yet implemented.
- https://github.com/jhipster/prettier-java/blob/88caf362d34d7e02ad43b83a8448ac696cb7fcdd/packages/java-parser/src/tokens.js#L156-L157

So some restrictedKeywords are dependent on **Parser Context**.
I think this can be solved by creating many kinds of "token categories"
that could match different sets of allowed identifiers.
