### ISSUE TITLE
Dev Dependencies does not extend to subprojects

### ISSUE THREAD

**Issue by Hawkurane** [jhipster/prettier-java#149]
Using npm install in prettier-java only installs mocha and npm-run-all in the node_modules folder for the prettier-java project. Running
```bash
npm test
```
In the java-parser project results in searching the node packages mocha and npm-run-all in the node_modules folder in the java-parser project and not the prettier-java project one.
Since they are not declared in the devDependencies, the test command will fail.

**Comment by bd82** [comment]
https://github.com/lerna/lerna#lernajson

> The packages config in lerna.json is a list of globs that match directories containing a package.json, which is how lerna recognizes "leaf" packages (**vs the "root" package.json, which is intended to manage the dev dependencies and scripts for the entire repo**).

**Comment by Hawkurane** [comment]
I'm still new to lerna, I don't seem to be able to run tests without installing mocha and npm-run-all manually.

**Comment by bd82** [comment]
Are you using Yarn or npm?

https://github.com/jhipster/prettier-java/blob/master/CONTRIBUTING.md#contributing-to-prettier

**Comment by Hawkurane** [comment]
I am using npm mainly, I currently cannot try out right now but will probably later in the weekend

**Comment by bd82** [comment]
You should use yarn in this project as it support workspaces with lerna and would make sure to install all required dependencies and link them.

**Comment by Hawkurane** [comment]
Hello again, it seems i've managed to make it work as intended. Thanks for linking the mini-guides, it seems I missed it...
However, it is really slow, especially when running tests. Is there any way to speed up the process except by running the scripts manually with mocha/npm-run-all installed?
Is there a possibility to switch to npm only as well? It seems JHipster will generally lean towards using npm instead of yarn.

**Comment by bd82** [comment]
> However, it is really slow, especially when running tests. Is there any way to speed up the process except by running the scripts manually with mocha/npm-run-all installed?

Running tests would be slow from the root package.json as it would always re-clone the example repos.
I generally run tests directly from webstorm.

You can also run the tests without cloning in the java-prser package by running:
> yarn run test:execute

- Using yarn will resolve the mocha CLI command correctly.

Your question is basically how to execute a mocha command line in your dev env.
A very  ugly but simple solution would be to install mocha **globally**.
Or better yet see how to execute mocha from inside your favorites IDE.

> Is there a possibility to switch to npm only as well? It seems JHipster will generally lean towards using npm instead of yarn.

Lerna supports npm too. the initial bootstrapping of the project would be slower
as npm does not support mono repo workspaces natively, but it could be used.
I generally prefer yarn, but I am no longer taking the lead in this project
so you are free to choose and modify the dev env and flows...
