### ISSUE TITLE
Question: which branch to test

### ISSUE THREAD

**Issue by benjavalero** [jhipster/prettier-java#151]
I would like to help a little, at least testing against code from myself.

I have found that branch "cst-print" produces more complete formatted code, so I guess this is the branch to be tested. Could you confirm if I am right?

Kind Regards,

**Comment by clement26695** [comment]
Hi ! Thank you for your help ! 

I started working on the printer in the cst-print branch. It is far from being complete, but it is the most up-to-date branch concerning the printer.

Concerning the parser, I think the most up-to-date branch is master

**Comment by bd82** [comment]
This will start getting messy very quickly...

Best case scenario would be for @clement26695 to get the cst-print to a "green" state (tests/linting passing) and merge to master and then we won't have future merge conflicts.

Future work on the CST printing should probably be done in smaller PRs/Commits

**Comment by benjavalero** [comment]
Thanks for your answers. I will wait then to the "cst-print" branch to be merged into master.

In case it may help before this merge, I have found the following issues:
- Extra spaces after the keyword `try` in a try-catch block
- No white lines between methods
- Annotations in the same line that the variable/method
- Error on parsing enumerations values like: `public enum WikipediaNamespace {
    ARTICLE(0),
    ...
}`

Please, tell me if I should open issues for them or just wait to the merge and test again.

**Comment by lipis** [comment]
@benjavalero I think regardless it's OK to open all these issues and keep track of them. If they are going to be fixed with the merge, they will get closed. But it's better to track as much as possible, to get the whole idea of what's missing.

**Comment by bd82** [comment]
@clement26695 Do you have any estimate when you would be able to merge the cst-branch back to master?

Large long lived side branches are a recipe for trouble 😈

**Comment by clement26695** [comment]
Sorry, didn't had much time to work on this lately. It is close to be ready to merge, I just wanted to fix one printer before merging

**Comment by bd82** [comment]
Awesome 👍

**Comment by bd82** [comment]
CST branch was merged to master
