### ISSUE TITLE
Integration with travis is semi broken

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#160]
No pull request status checks posted, but it does seem like they are being run.

**Comment by bd82** [comment]
https://travis-ci.org/jhipster/prettier-java

**Comment by bd82** [comment]
@jdubois I do not have permissions to modify travis settings.
Could you try to re-enable travis for this repo?

Perhaps the transitions to teams based permissions messed something up?

**Comment by clement26695** [comment]
I think it is fixed, now
