### ISSUE TITLE
Reinforcing tests for the prettier-plugin-java package

### ISSUE THREAD

**Issue by Hawkurane** [jhipster/prettier-java#186]
Right now, we have a set of short samples and all it does is compare the output to an expected output. We should supplement additional tests to ensure the plugin still works as intended, especially as we are currently modifying it so it can print commentaries. Plus, it might be a problem for maintainability when we change the expected output in the future. 

Here a few ideas:

- [ ] Supplement the current samples with longer and better ones. With a lot of commentaries to make sure they are printed correctly.
- [ ] Find another way to test the prettier-plugin: prettify a repo that has correctly installed tests, and run them to make sure they are still functional
- [ ] ~Prettify a repo, remove all the whitespaces in both input and output and compare them to each other.~

Any ideas welcomed !

**Comment by bd82** [comment]
- [ ] verify the output compiles with javac or another java compiler/parser.
     - But this means we need the input to be semantically valid too, not just syntactically valid.

**Comment by bd82** [comment]
btw why is the current setup unsuitable for testing comment printing?

**Comment by Hawkurane** [comment]
It's just that the current samples don't have any (or very few) commentaries. I just meant it in the way that the samples should have some commentaries to ensure they are printed.

**Comment by bd82** [comment]
> It's just that the current samples don't have any (or very few) commentaries. I just meant it in the way that the samples should have some commentaries to ensure they are printed.

o.k I understand, the content needs to be expanded for that case, not the infrastructure,
