### ISSUE TITLE
CLI Implementation

### ISSUE THREAD

**Issue by Hawkurane** [jhipster/prettier-java#188]
Hello,
Do we need to implement a CLI for prettier-java?
From what I understand this is supposed to be hooked onto the main prettier module and be used as a plugin but I do not quite understand how it is supposed to be working.

@bd82

**Comment by bd82** [comment]
https://prettier.io/docs/en/plugins.html#using-plugins

> Plugins are automatically loaded if you have them installed in the same node_modules directory where prettier is located. Plugin package names must start with @prettier/plugin- or prettier-plugin- or @<scope>/prettier-plugin- to be registered.
