### ISSUE TITLE
Releasing new versions

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#191]
I will update the contribution guide with relevant instructions and someone else will hopefully trigger a release of the new versions.

**Comment by bd82** [comment]
I am simply not getting around to this...

## Some hints to whomever wants to handle this.
The release process should very similar to the one I use in Chevrotain.
- https://github.com/SAP/chevrotain/blob/master/CONTRIBUTING.md#release-process

The build process would need to be modified to have a special release build that would be trigger on tag pushes, This is how I do it with CircleCI, I am sure something similar is possible in AzureDevOps
- [Release Build Definition](https://github.com/SAP/chevrotain/blob/94a21a767d50378bedf8404a7a049d02e7bb936c/.circleci/config.yml#L33-L49)
- [Release Build Trigger](https://github.com/SAP/chevrotain/blob/94a21a767d50378bedf8404a7a049d02e7bb936c/.circleci/config.yml#L58-L63)

Additionally for the release build trigger to work an NPM_TOKEN env variable must be made
available during the build. It is possible to obtain one from npmjs.com web UI once logged in.

**Comment by jdubois** [comment]
Yes I believe it is time for a new release, this is what will make the project go final.

I will have a look today but I'm probably not the best one - who would be interested? I think this is worth some bug bounty, I'll configure this later once I've seen the amount of work needed.

**Comment by Shaolans** [comment]
@bd82 Hello, I think we should release now a new version of prettier-java. WDYT ?
I think we have currently have a pretty good result if not perfect and it would be great to have some user feedbacks. Plus, I am seeing people trying to use but cannot since the npm prettier-java is the old one.

**Comment by clement26695** [comment]
You can look at clement26695/jhipster-sample-app#2 to look at the result of formatting on the JHipster sample app

**Comment by clement26695** [comment]
@Shaolans, I think we should revert b602ad80d0d94e09276a9e8cac2e2bb3fd919482 first

**Comment by bd82** [comment]
@clement26695 @Shaolans 

I would prioritize sorting out an automated release process.
Then each release would be a simple command and you can release as many versions as you want per day...

**Comment by bd82** [comment]
I just released 0.3.1

- The release command is : "yarn run lerna:version" (you can see it in the package.json).
- The trigger happen in travis and should be migrated to AzureDevops
- The auth uses npm_tokens (please add one of your own on azureDevops so I can remove mine).
- The release command is not enough, a process should be built around it (e.g updating changelog or even generating a changelog automatically).

I strongly suggest weekly releases (at max) maybe even per feature/fix releases, when the release is automated there is no need to wait months between releases... lets be more agile and incremental 😄 

Cheers.

**Comment by jdubois** [comment]
@bd82 this is really important, and on the main project we (= @pascalgrimaud ) have a huge experience with Azure Devops.

I think we should add a bug bounty on this, to speed things up -> is that fine if I put it on this ticket?

**Comment by bd82** [comment]
With AzureDevOp you just need to:
1. inject a secure variable that contains the NPM_TOKEN
   - [Relevant Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)
2. execute a conditional build on tag pushes that executes the [deploy.sh script](https://github.com/jhipster/prettier-java/blob/master/.travis.yml#L22)
   - [Example](https://github.com/vega/ts-json-schema-generator/blob/master/azure-pipelines.yml#L61-L66)

It does not seem particularly complex although Azure PipeLines do seem more complex than it needs be which is why I'm sticking with CirclecCI for my projects...

**Comment by clement26695** [comment]
I'll try to take care of that this weekend or on Monday

**Comment by pascalgrimaud** [comment]
I can help you @clement26695 if needed
The only problem is to generate an NPM_TOKEN which will work, as I'm using 2FAS auth with NPM. Hope it will work with token
