### ISSUE TITLE
Update README.md files

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#192]
I think it is time to update the main and child readme.md files.
e.g:
- There is no readme.md for prettier-plugin-java
  - https://github.com/jhipster/prettier-java/tree/master/packages/prettier-plugin-java

- The root readme roadmap is probably mostly done or irrelevant by now.

- The root readme should link to the sub packages of this mono repo.

**Comment by n-peugnet** [comment]
Hey, I'm very interested in your project, but I'm not sure how to try it.

While you are updating the root README could you add some hints about how to use it ?

**Comment by bd82** [comment]
Good point.
@clement26695 @Shaolans does one of you want to take over this?
