### ISSUE TITLE
Setting up prettier-java for Azure Pipelines

### ISSUE THREAD

**Issue by Shaolans** [jhipster/prettier-java#195]
Since we will migrate our CI from Travis CI to Azure Pipelines, we need to set up the project in the JHipster organization on Azure. :smile:

**Comment by pascalgrimaud** [comment]
Thanks. I'll do it asap

**Comment by bd82** [comment]
Cool I would be interested in seeing a working example of Azure Pipelines.
I've only used circle-ci/Travis so far.
