### ISSUE TITLE
Organize imports ?

### ISSUE THREAD

**Issue by clement26695** [jhipster/prettier-java#201]
Should we ordered imports as in the following guides ?

https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing

or 

https://github.com/spring-projects/spring-framework/wiki/Code-Style

**Comment by bd82** [comment]
What does prettier-javascript do for ES6 imports?

**Comment by j-f1** [comment]
Prettier JS does not order imports because they can have side effects that could conflict, but if Java doesn’t have that issue, then you should be fine with sorting imports.

**Comment by jdubois** [comment]
No problem in Java, but I don't think we can optimize "*" in imports, or clean up unused imports, as we have no way to know the classes that are being used for real.

**Comment by Shaolans** [comment]
Yes, we can only reorder the imports and how should we reorder it ? both of the guides looks good to me..

**Comment by lppedd** [comment]
Google style should be preferred as it exists from more time (more than I can remember).
Imports should be ordered by domain (net, org, com, [it, de, ...] and alphabetically, imho.

**Comment by murdos** [comment]
Maybe it's already implied, but it would be nice if duplicated imports would be removed too.

**Comment by bd82** [comment]
> Maybe it's already implied, but it would be nice if duplicated imports would be removed too.

Should that be the responsibility of a **formatter**?

**Comment by jhaber** [comment]
Reformatting imports according to Google's style guide sounds like a great addition 👍

**Comment by bd82** [comment]
> Reformatting imports according to Google's style guide sounds like a great addition 👍

You mean this?
- https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

Note that some of the rules there seem like linting/semantic rules and not pure syntax rules.
So those are probably not the responsibility of a prettier plugin.

**Comment by jhaber** [comment]
> Note that some of the rules there seem like linting/semantic rules and not pure syntax rules.
> So those are probably not the responsibility of a prettier plugin.

Agreed, I was imagining prettier-java would handle:
3.3.2 No line-wrapping
3.3.3 Ordering and spacing

And for the other two to be out of scope:
3.3.1 No wildcard imports
3.3.4 No static import for classes

**Comment by clement26695** [comment]
It seems doable. I'll try to do a simple implementation that we could refine in the future if needed/wanted

**Comment by clement26695** [comment]
PR done. The reformating would be as follow:

Input:
```java
package my.own.pkg;
import something.Different;
import java.utils.*;;;
import abc.def.Something;
import abc.def.Another;;;
import  static something.Different;
import static  java.utils.*;;;
import static abc.def.Something;
import static abc.def.Another;;;
import one.last;;;

public class PackageAndImports {}
```

Output:
```java
package my.own.pkg;

import static abc.def.Another;
import static abc.def.Something;
import static java.utils.*;
import static something.Different;

import abc.def.Another;
import abc.def.Something;
import java.utils.*;
import one.last;
import something.Different;

public class PackageAndImports {}
```

**Comment by aqelkp** [comment]
How do I disable this rule? This is messing up with my intellij auto import formatting.

**Comment by pascalgrimaud** [comment]
@aqelkp : I don't know if it's possible to disable it (I'll let other people to answer to this question), but about me, I changed the default config in Intellij to use the same rule than prettier and it works well

**Comment by aqelkp** [comment]
@pascalgrimaud I did quick search and I couldn't get a solution for this in IntelliJ. Can you please share the solution you used for IntelliJ?

**Comment by pascalgrimaud** [comment]
@aqelkp : here my config with a screenshot

![intellij_import_config](https://user-images.githubusercontent.com/9156882/81388728-fd1cff00-9118-11ea-83d9-57f54297278c.png)

**Comment by aqelkp** [comment]
@pascalgrimaud Thanks a ton 😄

**Comment by pascalgrimaud** [comment]
@aqelkp : you're welcome

@clementdessoude : maybe we should document it ? What do you think ?
