### ISSUE TITLE
Unknown java node DO_WHILE_STATEMENT

### ISSUE THREAD

**Issue by n-peugnet** [jhipster/prettier-java#211]
```
Unknown Java node: { type: 'DO_WHILE_STATEMENT',
  body: { type: 'BLOCK', statements: [ [Object], [Object] ] },
  condition:
   { type: 'OPERATOR_EXPRESSION',
     left: { type: 'IDENTIFIER', value: 'foundReadyThread' },
     operator: { type: 'OPERATOR', operator: '==' },
     right: { type: 'NULL' } } }
```

```java
	private ParallelLoaderRunnable getReadyThread() {
		ParallelLoaderRunnable foundReadyThread = null;
		do {
			for (int iThread = 0; iThread < threadCount; iThread++) {
				if (runnableArray[iThread].tryUseForNewDataCollection()) {
					foundReadyThread = runnableArray[iThread];
					//Log.error("trouvé - iThread=" + iThread);
					//Timer t = new Timer("GC temps pris");
					//System.gc();
					//t.log();
					//Log.error("Thread trouvé !!");
					break;
				}
			}
			if (foundReadyThread == null) {
				//Log.error("Attente d'un thread dispo...");
				try {
					Thread.sleep(5); // attente mi-active
				} catch (Exception e) {
					Log.error(e);
				}
			}
		} while (foundReadyThread == null);
		return foundReadyThread;
	}
```

The full file [can be found here](https://github.com/slipsoft/slipdb/blob/bc42c0ec80f217f11c482175e95f0bc6b8c034ce/src/main/java/db/data/load/ParallelLoader.java).

There are also a lot of problems with disappearing comments but I will file a new issue for this other problem.

**Comment by clement26695** [comment]
Hi ! I just tried your file, and it seems to be parsed and printed without error on the current version of master. 
The version published on npm is not working properly for the moment, but we will try to release it very soon (in the coming week, or the next one, hopefully), once fixed a few last bugs on line wrapping.

In the meantime, if you want to test the latest version of the plugin, you can follow the instruction on the install section of the readme: https://github.com/jhipster/prettier-java#install

Anyway, thank you for reporting the issue ! 😄
