### ISSUE TITLE
yarn ci command is failing on Windows machines

### ISSUE THREAD

**Issue by PiiSmith** [jhipster/prettier-java#252]
How do you build the project locally? I want to try the newest features (like [this ](https://github.com/jhipster/prettier-java/commit/83a6ccc6b234253f2dda0956e9a3da80234b41c0)) on my project.

I tried running `yarn ci`, but this gives me following error:
```
$ yarn ci
yarn run v1.17.3
$ npm-run-all build lint format:validate test
$ node packages/java-parser/scripts/unicode.js packages/java-parser/resources/Unicode/UnicodeData.txt; prettier --writepackages/java-parser/src/unicodesets.js; node packages/java-parser/scripts/gen-diagrams.js
D:\ccviews\JavaNG\prettier-java\packages\java-parser\scripts\unicode.js:92
    throw Error("Please specify the path of the UnicodeData.txt file");
    ^

Error: Please specify the path of the UnicodeData.txt file
    at readUnicodeData (D:\ccviews\JavaNG\prettier-java\packages\java-parser\scripts\unicode.js:92:11)
    at Object.<anonymous> (D:\ccviews\JavaNG\prettier-java\packages\java-parser\scripts\unicode.js:241:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also would be possible to do release again?

**Comment by clement26695** [comment]
Yes, we'll try to do a release soon !

Concerning your issue, you are using Windows, right ? I believe it can come from the file path here, which should be different in windows: https://github.com/jhipster/prettier-java/blob/98dc1f6314fe6780bb50be56c21368aa7f82c973/package.json#L18

Would it be possible to update it with backslashes instead of slashes to see if it resolve the issue? 
packages/java-parser/resources/Unicode/UnicodeData.txt => packages\java-parser\resources\Unicode\UnicodeData.txt

**Comment by PiiSmith** [comment]
Yes, I am using windows, but I tried the git bash, as well as the windows command prompt. Both give me the same problem.

From my tries it seems to be about the ";" at the end of the file name:
` "build": "node packages/java-parser/scripts/unicode.js packages/java-parser/resources/Unicode/UnicodeData.txt prettier --write packages/java-parser/src/unicodesets.js; node packages/java-parser/scripts/gen-diagrams.js", `
As you can see in the line above, if I leave it out the build continues. Then runs into this Problem:
```
yarn run v1.17.3
$ npm-run-all build lint format:validate test
$ node packages\java-parser\scripts\unicode.js packages\java-parser\resources\Unicode\UnicodeData.txt prettier --write packages\java-parser\src\unicodesets.js; node packages\java-parser\scripts\gen-diagrams.js
$ eslint packages/**/*.js
$ prettier --list-different "**/*.@(js|json|md)"
packages\java-parser\src\unicodesets.js
packages\prettier-plugin-java\test\unit-test\extends_abstract_class_and_implements_interfaces\extends_abstract_class_anderror Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "format:validate" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I guess it is again about slight differences in the line endings or something similar, which makes the test fail.

How can I just build the project without doing any tests? I just want to build the package so I can copy it to my node_modules directory and use it there.

**Comment by bd82** [comment]
I reproduced on windows using git bash as the terminal.

I resolved this by replacing the semicolons with `&&` in this line
https://github.com/jhipster/prettier-java/blob/master/package.json#L18

**Comment by jdubois** [comment]
@clement26695 @pascalgrimaud how hard would it be to have automated build after each commit, like a "snapshot" version with Maven? This would be worth a good bug bounty in my opinion!!

**Comment by bd82** [comment]
-  npm supports tagged releases, e.g TypeScript releases a nightly build
    - [TypeScript delivers nightly builds](https://www.typescriptlang.org/docs/handbook/nightly-builds.html)

- We need:
  -  a trigger on azure
  - Different lerna commands flow:, e.g **not** use `lerna publish **from-git** --yes`

I think its not super hard, but can have minor integration difficulties.
I also think a nightly release would suffice.

BTW triggering a **regular** release is just a matter of running an npm script.
There really is no reason not to spend a few seconds running the script (+10mins updating the changelog) once a week...

**Comment by PiiSmith** [comment]
To have more regular releases is fine and I am all for it. My problem is just building the project locally, so  I can use it on one of my Java projects.
What can I do to just get a new package built w/o doing any of the tests?

**Comment by clement26695** [comment]
Can you try the fix proposed by @bd82 and replace the *;* by *&&* in https://github.com/jhipster/prettier-java/blob/master/package.json#L18. I made a PR (#253) to include this fix, but I can't test it as I don't have any Windows devices. 

To use the plugin, you just need to indicate from where it is loaded, and it should be ok :

```bash
# Example where the plugin is locate in node_modules
prettier --write MyJavaFile.java --plugin=./node_modules/prettier-plugin-java
```

**Comment by pascalgrimaud** [comment]
@jdubois : not hard to automate the release, the only issue is to find time to do it
- configure a specific pipeline on Azure
- add secret key in private environment variables
- schedule the pipeline

**Comment by jdubois** [comment]
Agreed, that needs time, so this is worth a bug bounty if want this to move forward!

**Comment by PiiSmith** [comment]
> 
> 
> Can you try the fix proposed by @bd82 and replace the _;_ by _&&_ in https://github.com/jhipster/prettier-java/blob/master/package.json#L18. I made a PR (#253) to include this fix, but I can't test it as I don't have any Windows devices.
> 
> To use the plugin, you just need to indicate from where it is loaded, and it should be ok :
> 
> ```shell
> # Example where the plugin is locate in node_modules
> prettier --write MyJavaFile.java --plugin=./node_modules/prettier-plugin-java
> ```

I used the change from this commit and it helped me to get past the first error I reported.

Then I got held up by a very similar problem, so I further changed this line to:
`"build": "node packages/java-parser/scripts/unicode.js packages/java-parser/resources/Unicode/UnicodeData.txt && prettier --write packages/java-parser/src/unicodesets.js && node packages/java-parser/scripts/gen-diagrams.js",`
(Note the 2nd &&)

After this there a problem with GIT and long file names in windows, which I resolved via:
`git config --global core.longpaths true`

Now I can get past a lot of tests, where a lot of Java is parsed.
There the test with the jhipster-sample-app fails:
```
prettier-plugin-java:       3) verify semantic validity D:\prettier-java\packages\prettier-plugin-java\samples\jhipster-sample-app
prettier-plugin-java:   5787 passing (57s)
prettier-plugin-java:   3 failing
prettier-plugin-java:   1) prettier-java
prettier-plugin-java:        Prettify the repository <D:\prettier-java\packages\prettier-plugin-java\samples\spring-boot>
prettier-plugin-java:          verify semantic validity D:\prettier-java\packages\prettier-plugin-java\samples\spring-boot:
prettier-plugin-java:      TypeError: Cannot read property 'toString' of null
prettier-plugin-java:       at Context.<anonymous> (test\test-utils.js:99:87)
prettier-plugin-java:   2) prettier-java
prettier-plugin-java:        Prettify the repository <D:\prettier-java\packages\prettier-plugin-java\samples\jhipster>
prettier-plugin-java:          verify semantic validity D:\prettier-java\packages\prettier-plugin-java\samples\jhipster:
prettier-plugin-java:      TypeError: Cannot read property 'toString' of null
prettier-plugin-java:       at Context.<anonymous> (test\test-utils.js:99:87)
prettier-plugin-java:   3) prettier-java
prettier-plugin-java:        Prettify the repository <D:\prettier-java\packages\prettier-plugin-java\samples\jhipster-sample-app>
prettier-plugin-java:          verify semantic validity D:\prettier-java\packages\prettier-plugin-java\samples\jhipster-sample-app:
prettier-plugin-java:      TypeError: Cannot read property 'toString' of null
prettier-plugin-java:       at Context.<anonymous> (test\test-utils.js:99:87)
prettier-plugin-java: error Command failed with exit code 3.
prettier-plugin-java: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
prettier-plugin-java: ERROR: "test:e2e-core" exited with 3.
prettier-plugin-java: error Command failed with exit code 1.
prettier-plugin-java: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in 'prettier-plugin-java'
error Command failed with exit code 1.
```

**Comment by clement26695** [comment]
Yes, you should be able to use the package without ever using the `yarn ci`command. 

I'll try to investigate what could go wrong with doing the tests on Windows when I'll find a Windows machine, starting with what @bd82 suggested.

Concerning automating the pipeline, we'll try to set up that in the next days with @pascalgrimaud.

**Comment by clement26695** [comment]
@PiiSmith we published a new version on npm. You can try java-parser@0.3.2 and prettier-plugin-java@0.3.2
