### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by jjuel** [jhipster/prettier-java#254]
So this isn't really an issue (unless you consider it a documentation issue), but I was curious about the usage of this plugin. So everything does work as expected on single files. Is there a way to run this on every file in a Java project (either from command line or in an IDE)? If this is the wrong place for posting this please feel free to close this issue. I am just trying to figure it out, and there isn't much in terms of usage documentation out there.

**Comment by Shaolans** [comment]
Hello @jjuel,
As you said, prettier-java is a plugin, it adds the support of Java for Prettier. You should be able to run Prettier command without any issues. For instance, if you want to run and write every java file in a projet you can run:
```bash
prettier --write myproject/**/*.java
```

**Comment by jjuel** [comment]
Well I guess it would have helped if I would have looked into how Prettier itself worked. That is my bad. Thank you for the help.
