### ISSUE TITLE
Inspect NPM_TOKEN used

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#258]
I think the publishing process may be using my personal NPM token (not sure).
Anyhow if it does I've recently reset my npm token making any pre-existing tokens invalid.

We may need to insert a new NPM_TOKEN secret to azure-devops
We may also want to create a BOT user for publishing to avoid using "personal" npm tokens.

**Comment by bd82** [comment]
@pascalgrimaud @clement26695 Please have a look.

**Comment by clement26695** [comment]
We used @pascalgrimaud token, but it didn't work as he uses Two factor Authentification. We will have to take a look to solve this issue, but indeed, using a specific user/bot with limited access looks like a good idea !
