### ISSUE TITLE
Javadoc in Enums

### ISSUE THREAD

**Issue by PiiSmith** [jhipster/prettier-java#259]
When using the Prettier built from the current master on Enums with Javadoc comments, those get moved around in a way, that does not make sense.

Start with this example:
```
/**
 * test enum
 */
public enum test {
    /** TEST1 Javadoc */
    TEST1,
    
    /** TEST2 Javadoc */
    TEST2
}
```

It gets "prettified" to this:

```
/**
 * test enum
 */
public enum test {
    /** TEST1 Javadoc */
    TEST1, /** TEST2 Javadoc */
    TEST2;
}
```

It is clear visible, that the prettified state is not better readable or conform to some norm, compared to the original.

**Comment by clement26695** [comment]
Thank you for reporting this ! Will try to fix it :)

**Comment by clement26695** [comment]
Should be better now that #278 is merged

**Comment by jhaber** [comment]
I think #319 also helped with this, on master I'm now seeing output of:
```java
/**
 * test enum
 */
public enum test {
  /** TEST1 Javadoc */
  TEST1,
  /** TEST2 Javadoc */
  TEST2
}
```

**Comment by PiiSmith** [comment]
I just wanted to say Thank You! With this correction the plugin is now in use for our code.
