### ISSUE TITLE
Parser Initilization Time

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#269]
It seems to take well over 100ms on my machine for the Parser to initialize.
There is now an official guide how to speed the initialization time:
https://sap.github.io/chevrotain/docs/guide/initialization_performance.html#enabling-initialization-performance-tracing

Please report on the results, additional upgrades can be implemented for faster init time as needed...

Also note that enabling the init perf tracing affects the initialization time due to many (synchronized) console printing. So the real performance number is best achieved with a simple
timer. 

```
const start = new Date.getTime();
// do smt
const end = new Date.getTime();
const total = end - start;
```

**Comment by pascalgrimaud** [comment]
Adding a bounty on this

**Comment by bd82** [comment]
I could have a look at this on the weekend, should I assign myself to it?

**Comment by clement26695** [comment]
Yes, go ahead ! 😄

**Comment by clementdessoude** [comment]
Just a reminder: do not forget to claim your bounty @bd82, you deserve it :)

**Comment by bd82** [comment]
All these forms are too complicated for me additionally paypal annoyed me so I closed my account there 😄 .

You can use this 100$ for some other bounty..
