### ISSUE TITLE
Blank line removed after class declaration

### ISSUE THREAD

**Issue by murdos** [jhipster/prettier-java#271]
This might be done on purpose, but I'm opening this issue to be able to discuss it.
Before:
```
public class JWTFilter extends GenericFilterBean {

    public static final String AUTHORIZATION_HEADER = "Authorization";

    private TokenProvider tokenProvider;
```

After:
```
public class JWTFilter extends GenericFilterBean {
    public static final String AUTHORIZATION_HEADER = "Authorization";

    private TokenProvider tokenProvider;
```

I think it would be more readable to add/keep the extra line.

In the following example it's hard to distinguish between the end of the class declaration (and its superclass and interfaces) and the first field:
```
public class MyLoooooongClass
    extends AbstractAuditingEntity
    implements Serializable, MyInterface<AAAAAAA, BBBBBBBBBBB> {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
```

Also if the first "content" of the class is an inner class the blank line is added:
```
 /**
 * some javadoc
 */
public class MyEntityCriteria implements Serializable, Criteria {

    /**
     * Class for filtering MyEntity
     */
    public static class MyEntityFilter extends Filter<MyEntity> {

        public MyEntityFilter() {}
```

**Comment by clement26695** [comment]
@murdos Do you think we should always add a blank line at the beginning of class bodies and interfaces bodies ?

**Comment by murdos** [comment]
Yes, that's what I would like (when there's a non empty body of course).
But I'm not sure there's a consensus.

**Comment by pascalgrimaud** [comment]
Adding a bounty on this

**Comment by benjavalero** [comment]
> @murdos Do you think we should always add a blank line at the beginning of class bodies and interfaces bodies ?

What about the end of a class? It usually contains a method, so after formatting there is no blank line between the ending `}` of the method and the ending `}`of the class.

**Comment by jhaber** [comment]
> > @murdos Do you think we should always add a blank line at the beginning of class bodies and interfaces bodies ?
> 
> What about the end of a class? It usually contains a method, so after formatting there is no blank line between the ending `}` of the method and the ending `}`of the class.

I don't think adding a newline between the last method and end of class is a common style so I would advocate for prettier not doing it. 

In terms of adding a newline at the beginning of a class, I think there are definitely cases where this improves readability. And in the cases where it doesn't seem necessary, it doesn't actively _harm_ readability (it's just a minor annoyance that people will get used to). So I would be in favor of keeping the behavior simple/predictable and unconditionally adding a newline at the beginning of a class declaration

**Comment by digorydoo** [comment]
Why not enforcing the newline only when the class declaration wrapped around? E.g. when it does not wrap around, do:

```
public class MyEntityCriteria implements Serializable, Criteria {
    public static class MyEntityFilter extends Filter<MyEntity> {
    }
}
```

and when it does:

```
public class MyEntityCriteria
    implements Serializable, SomeVeryLongishNameForCriteria {

    public static class MyEntityFilter extends Filter<MyEntity> {
    }
}
```

**Comment by noahbetzen-wk** [comment]
I feel like this could easily be added as a configuration option.

**Comment by mmadson** [comment]
Are there plans to merge #398 ? This particular issue has me on the fence about adopting prettier for our java project.

**Comment by lamergameryt** [comment]
How do you overwrite this behavior in the `.prettierrc.yml` file? I would like prettier to not add an extra blank-line after classes.
