### ISSUE TITLE
Remove "hacky" fix for CST Building while backtracking

### ISSUE THREAD

**Issue by clement26695** [jhipster/prettier-java#272]
We can now remove this "hack" since it was fixed in the new releases of Chevrotain.

See: https://github.com/jhipster/prettier-java/blob/73a888d5e0df2bb206364088cc9c6740c197a573/packages/java-parser/src/parser.js#L148-L154 and SAP/chevrotain#789

I assign this to @Shaolans since he coded the prettier-ignore support which could be affected here. Please let me know if you don't have time to look at it, and I'll try to do it

**Comment by bd82** [comment]
I think the CSTNode is build but the position information is not added to it nor is it added to its parent CSTNode.

- https://github.com/SAP/chevrotain/commit/1dc658e27c12a097b279bbcf48bb4c287c7f1982#diff-2e10783ac7c5b55b9ab1cd01b7988691

You could disable comment tracking logic while backtracking as well...
