### ISSUE TITLE
Support for Java 13

### ISSUE THREAD

**Issue by Gameghostify** [jhipster/prettier-java#277]
Support for Java 13 and language previews such as [JEP 355: Text Blocks](https://openjdk.java.net/jeps/355) would be awesome.

Thoughts?

**Comment by bd82** [comment]
Related question: Is Java 13 fully backward compatible (syntax wise) with Java 12?

**Comment by clement26695** [comment]
Yes, I thought about this one, but didn't had the time to investigate if there were some breaking changes. It seems that the changes in the grammar are listed here:

- For switch expression: https://docs.oracle.com/javase/specs/jls/se13/preview/switch-expressions.html
-  For text blocks: https://docs.oracle.com/javase/specs/jls/se13/preview/text-blocks.html

I would say that it should be easy to integrate text blocks in the grammar, as it is just an addition and does not impact much. For switch expressions, it could be more difficult, but I don't know yet

**Comment by bd82** [comment]
The question is: `Do we want to have separate parsers/formatters for separate Java Versions? or a single Parser that supports all?`

The answer probably depends on the backward compatibility of syntax extensions in Java 13.

Regarding priorities, I tend to agree that stabilizing and finalizing Java 12 support seems more important.

**Comment by Gameghostify** [comment]
> Related question: Is Java 13 fully backward compatible (syntax wise) with Java 12?

It should be fully backward compatible, I'm pretty sure. There are only non-breaking additions to the syntax, which are language previews, like the new switch expressions and text-blocks JEPs @clement26695 mentioned

**Comment by Artur-** [comment]
Should this be changed into "Java 15" or "text blocks" suppport? Text blocks are no longer a preview feature and trying to format files with text blocks result in
```
Error: Sad sad panda, parsing errors detected in line: 17, column: 25!
[error] Expecting --> ')' <-- but found --> '"
```

**Comment by clementdessoude** [comment]
Hi @Artur- ! I give it a try to support TextBlocks. It seems to work, but as I am not using text blocks a lot, I'm not sure if I am missing some edge cases

**Comment by Artur-** [comment]
Can this be easily tested before there is a release? Or could you make a release?

**Comment by clementdessoude** [comment]
I'd like to merge #432 before doing a release, as it will cause some breaking changes. For now, you can use it locally by cloning the repo and using npm link or yarn link, but I hope I will manage to do a release soon :)
