### ISSUE TITLE
final keyword should stay on the same line

### ISSUE THREAD

**Issue by lppedd** [jhipster/prettier-java#282]
Esplicative GIF.
![Peek 14-10-2019 15-48](https://user-images.githubusercontent.com/19871649/66756345-1c60f000-ee9a-11e9-8a8a-47c780a7d0f1.gif)

Input:
```
final BackupStatus lastStatus = BackupStatus.fromDbValue(backupRepository.getLastStatus());
```

Expected output:
```
final BackupStatus lastStatus = 
{indent}BackupStatus.fromDbValue(backupRepository.getLastStatus());
```

This is on `master` branch.

**Comment by clement26695** [comment]
Indeed, thanks for reporting this !
