### ISSUE TITLE
Handle @formatter:off and @formatter:on ?

### ISSUE THREAD

**Issue by murdos** [jhipster/prettier-java#287]
`// @formatter:off` and `// @formatter:on` are commonly used and recognized by Eclipse and IntelliJ.
I wonder if prettier-java should handle them too, a bit like `// prettier-ignore`

**Comment by clement26695** [comment]
I thought of this one. I think we could/should do it, even if it is not supported by Prettier JS (for the moment): see https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwgJwFsBDGefJCHHAHShwFcowYBLaDeAZxgAoBKDMDoYMrHBl7cYg4VBox8cGA3xQMAQl4ATUnAAqrQnADq+YgAcLcfADoA5soCS2gRgC87jFAYAbXxgAPoEYjjAubp7efr6CAGRxGADyAEYAVnAsXLZwAI4MxL5cvGER-AA0GLrwhsZmltZ2pa78-ADcIhgAvnQ9UOjYeESk5JTy4wMWSmSsNgC0rPZQBHB0jMxsHNJucqLiktKydArTqupa1QZGpuZWNg7OLR5ePv5BIc2RLzHxiakZWRy+UKxU+FSqelqNwa9zB7U6fS6IHKIAgFk2UC4yFAxHw+AgAHcAAq4hBYlDEABuEFY2mRIBS5jAAGtlABlCzEMCsKD2ZCKBhwFEACxghF8JmFrG4nLAcDZZOlrEp0oAnshwFwsSieVwbDAieZ7CRkDgQUKQGkuAAPABCTNZMDZxGMABkeXBTeaUVbrWyefZfHAAIoMCDwL1FC2c-B6-AalLEFKq3zQelTHkwEy0mDC5AANgAHCiphA9fULBqpnA45TPSj8uG4Ia0eSQMQuHMoHA4Npe-SlPlWEpDcRjcRI3qUXrCKx+fhBdOA0HQ03JxaYEns9pc8gACwoxTEVi+AMAYQghBNKGW3fpDD1+iT5LNUa6XSAA

**Comment by lppedd** [comment]
This would also mean avoiding two different comments. Agree!

**Comment by pascalgrimaud** [comment]
Adding a bounty on this

**Comment by pascalgrimaud** [comment]
I'm increasing the bounty as there is more work than expected and you were more than 1 person to work on this, so you can share the bounty
