### ISSUE TITLE
Maven Plugin

### ISSUE THREAD

**Issue by jhaber** [jhipster/prettier-java#292]
Just wanted to give a heads up that we've written a Maven plugin that can be used to run prettier-java (either `check` or `write`): https://github.com/HubSpot/prettier-maven-plugin

It's available at the coordinates:
```xml
<plugin>
    <groupId>com.hubspot.maven.plugins</groupId>
    <artifactId>prettier-maven-plugin</artifactId>
    <version>0.5</version>
</plugin>
```

It has node, prettier, and prettier-java bundled so you don't need to worry about configuring those things in your CI environment

**Comment by clement26695** [comment]
Great news ! We should document this in our Readme

**Comment by jhaber** [comment]
We're also going to investigate running prettier-java in the JVM via the [graaljs script engine](https://github.com/graalvm/graaljs/blob/master/docs/user/ScriptEngine.md) so we don't need to bundle node or spawn a new process. 

Further down the line we're also thinking about having our developers run prettier as a daemon so that we're not paying repeated startup costs and hopefully the JIT will work its magic too
