### ISSUE TITLE
Docs for IDE integration

### ISSUE THREAD

**Issue by Graham42** [jhipster/prettier-java#30]
I think the most common current Java IDEs are probably IntelliJ and Eclipse. If there is integration with these editors, it would be awesome to have it documented so people coming from the Java world (perhaps very unfamiliar with JavaScritpt) can try this project out.

**Comment by thorbenvh8** [comment]
Ok yes we will work on it :) thanks for reminding me :)

**Comment by dminkovsky** [comment]
Is this possible and it's just undocumented?

**Comment by bd82** [comment]
In webstorm (JetBrains IDE for JavaScript) When I right click a file contents in a project that has prettier
configured I get a menu option called: "Reformat with Prettier".

Although I have not tested that this with prettier plugins and this would not help
someone who is not familiar with JavaScript eco system and does not know how to setup
a package.json and use npm...

Perhaps the scenario described here is to bundle this plugin a **self contained executable**
So it could be easily used in **pure** Java projects?

Anyhow this seems quite a long term goal, first we need to get this plugin to production quality...

**Comment by jdubois** [comment]
Personally I would just use Prettier as a Git pre-commit hook, so that it works everywhere, and I don't want to care about it inside my IDE - as long as the result is indeed production-ready, there's no added-value in checking what was updated.

**Comment by dminkovsky** [comment]
@bd82 

> that has prettier configured

You mean the project folder has a .prettierrc? Is there a plugin/functionality in Webstorm that reads it? I'm using IntelliJ and interested in integrating prettier-java specifically.

@jdubois 

That would work but I got used to using IntelliJ's Java code format to clean up code as I work on it. It's nice to see it cleaned up as I go along. And in Vim (for JS) I use pretter with ALE so there's a similar effect: type type type -> format (either by saving the file or explicitly) -> type type type. It's awesome to interact with prettier in real time that way.

**Comment by dminkovsky** [comment]
Oh thanks for this link! Right on that page it says:

> To use Prettier in IntelliJ IDEA, PhpStorm, PyCharm, and other JetBrains IDEs, please install this plugin.

I'll investigate that.

**Comment by hmeerlo** [comment]
@bd82 You closed the issue but it is unclear for me how to use prettier-java with IDEA. Can you explain how to configure it?

**Comment by bd82** [comment]
I think I closed it more because it was out of scope at the time (specifically the standalone binary flow).

Anyhow I do not actually use this plugin as I do not write Java Code 😄 

But this would be a good place to start:
- https://www.jetbrains.com/help/idea/prettier.html

The IDEA prettier plugin seems to assume you have prettier installed locally (e.g have a package.json and node_modules).

The Prettier website also contains relevant documentation.
- https://prettier.io/docs/en/webstorm.html

**Comment by bd82** [comment]
I have re-opened this in case anyone wants to provide more detailed docs/references, e.g in the README.md

**Comment by clementdessoude** [comment]
Hi @hmeerlo ! 

Can you give me your feedbacks about this [section](https://github.com/jhipster/prettier-java/blob/master/docs/advanced_usage.md#ide-integrations) ? Is this sufficient in your opinion or is it still unclear ?

**Comment by hmeerlo** [comment]
@clementdessoude Yes this was sufficient for me, thanks!
