### ISSUE TITLE
Multiline string indentation

### ISSUE THREAD

**Issue by jhaber** [jhipster/prettier-java#306]
I wanted to ask about the indentation of multiline strings. Here's an example of the behavior I'm seeing:

Input:
```java
public class Example {
  private static final String SQL =
    "INSERT INTO my_table (column_one, column_two) " +
    "VALUES (:value_one, :value_two) " +
    "ON DUPLICATE KEY UPDATE column_two = :value_two";
}
```

Output:
```java
public class Example {
  private static final String SQL =
    "INSERT INTO my_table (column_one, column_two) " +
      "VALUES (:value_one, :value_two) " +
      "ON DUPLICATE KEY UPDATE column_two = :value_two";
}
```

So the lines in the multiline string have mixed indentation. Is this intentional? Visually it seems nicer to have them aligned (might be less of an issue once [JEP 355: Text Blocks](https://openjdk.java.net/jeps/355) lands)

**Comment by clement26695** [comment]
Yes, I'm not sure why we put this indent. I thought PrettierJS was adding this indent too, but it doesn't seems the case

**Comment by jhaber** [comment]
IntelliJ seems to indent things this way by default, but it can be controlled via `Editor -> Java -> Wrapping and Braces -> Binary Expressions -> Align when multiline`

I'm not sure if there's an argument in favor of this style?

**Comment by benjavalero** [comment]
If the different lines are short, they are all formatted into the same line. I guess this is an expected behaviour:

Input:
```
String table = "{| class=\"wikitable\"\n " +
        "|-\n" +
        "| www.google.com\n" +
        "| Any text\n" +
        "|}";
```

Output (0.4.0):
```
String table = "{| class=\"wikitable\"\n " + "|-\n" + "| www.google.com\n" + "| Any text\n" + "|}";
```

However, if the short lines contain trailing comments, the comments are also formatted into the same line, and grouped at the end.

Input:
```
String falsePositiveListText = "Text\n" +
        "\n" + // Empty line
        " \n" + // Blank line
        " # A\n" + // Commented
        "A\n" + // No starting whitespace
        " B\n" +
        " b # X\n" + // With trailing comment
        " c\n" +
        " c\n"; // Duplicated
```

Output (0.4.0):
```
String falsePositiveListText =
    "Text\n" + "\n" + " \n" + " # A\n" + "A\n" + " B\n" + " b # X\n" + " c\n" + " c\n"; // Empty line // Blank line // Commented // No starting whitespace // With trailing comment // Duplicated
```
