### ISSUE TITLE
Indent after comment line

### ISSUE THREAD

**Issue by benjavalero** [jhipster/prettier-java#308]
After a comment line, if the block below is formatted, it gets unnecessarily indented.

Input:
```
// 1 result in DB by no type
Mockito.when(replacementRepository.findRandomArticleIdsToReview(Mockito.any(PageRequest.class)))
        .thenReturn(new ArrayList<>(Collections.singletonList(randomId2)));
```

Output (0.4.0):
```
// 1 result in DB by no type
    Mockito.when(
        replacementRepository.findRandomArticleIdsToReview(Mockito.any(PageRequest.class))
    ).thenReturn(new ArrayList<>(Collections.singletonList(randomId2)));
```

Expected output:
```
// 1 result in DB by no type
Mockito.when(
    replacementRepository.findRandomArticleIdsToReview(Mockito.any(PageRequest.class))
).thenReturn(new ArrayList<>(Collections.singletonList(randomId2)));
```

**Comment by jhaber** [comment]
Might be worth re-testing on master since 0.4.0 doesn't include #278

**Comment by murdos** [comment]
@clement26695: BTW it would nice to do a new release, since a lot of interesting things has landed in master 😉

**Comment by benjavalero** [comment]
> Might be worth re-testing on master since 0.4.0 doesn't include #278

I **think** I have retested against master and still get the same behaviour.

**Comment by clement26695** [comment]
I'll try to have a look when I have some time, probably next weekend. 

@murdos it was the plan to do one last weekend, but I got some computer issues unfortunately. I'll try to do one this weekend too !

**Comment by clement26695** [comment]
Just tested with master branch. When I try to format this :

```java
class T {
	void t() {
		// 1 result in DB by no type
Mockito.when(replacementRepository.findRandomArticleIdsToReview(Mockito.any(PageRequest.class)))
.thenReturn(new ArrayList<>(Collections.singletonList(randomId2)));
	}
}
```
I got this:

```java
class T {

  void t() {
    // 1 result in DB by no type
    Mockito
      .when(
        replacementRepository.findRandomArticleIdsToReview(
          Mockito.any(PageRequest.class)
        )
      )
      .thenReturn(new ArrayList<>(Collections.singletonList(randomId2)));
  }
}

```

with these options:
```sh
--print-width 80
--tab-width 2
```

**Comment by benjavalero** [comment]
Sorry, I wasn't using the master version of java-parser.

**Comment by clement26695** [comment]
Don't be sorry, it is really helpful to have your feedbacks! And we should improve our docs :)
