### ISSUE TITLE
Boolean expression assignment over multiple lines not indented

### ISSUE THREAD

**Issue by natdempk** [jhipster/prettier-java#311]
This seems similar to https://github.com/jhipster/prettier-java/issues/251 

I recently enabled this for my project and noticed that the second line of a boolean expression being assigned to a variable is not being indented, eg:

```java
boolean willDrop = predictDropResponse.getSendResult().isIgnorableFailure() ||
predictDropResponse.getSendResult().isFatalError();
```
I would expect this to be something like:
```java
boolean willDrop = predictDropResponse.getSendResult().isIgnorableFailure() ||
  predictDropResponse.getSendResult().isFatalError();
```

Indenting the second line of the boolean expression seems more consistent with how other multi-line assignments are handled.

**Comment by andybergon** [comment]
This seems to be true also for boolean expressions in lambdas and not only assignments.

e.g.
```
.filter(
  foo -> foo.isVeryVeryVeryLongConditionTrue() &&
  foo.isAnotherVeryVeryLongConditionTrue()
)
```

But I would expect to have continuation indent like this:
```
.filter(
  foo -> foo.isVeryVeryVeryLongConditionTrue() &&
    foo.isAnotherVeryVeryLongConditionTrue()
)
```

**Comment by jhaber** [comment]
It seems like it would be consistent with the rest of prettier-java style to linebreak after the equals if the entire assignment won't fit on the line. So the example in the issue description would become:
```java
boolean willDrop = 
  predictDropResponse.getSendResult().isIgnorableFailure() ||
  predictDropResponse.getSendResult().isFatalError();
```

This appears to be consistent with prettier-js as well. I think you could do the same thing in the lambda case too
