### ISSUE TITLE
Enum trailing commas get included on the same line as the semicolon ending the line

### ISSUE THREAD

**Issue by natdempk** [jhipster/prettier-java#313]
Enums that get split across multiple lines can lead to the last enum in the series having a `, ;` on the last line. If a `,` is specified after the last enum value that should be used as an indicator to create another newline and to place the `;` on that newline, or the `, ` should be dropped entirely and it should just become a `;` after the last enum value. 

I could see arguments for either option, but I'd prefer placing the `;` on a newline as this preserves version control history for the line with the previous enum value when a new value is eventually added.

Input:
```java
enum MyEnum {
  AAAAAAAA("aaaaaa"),
  BBBBBBBBBBB("bbbbbbbbbb"),
  CCCCCCCCCC("ccccccccc"),
  DDDDDDDDD("ddddddddddddddddddddddddd"),
  EEEEEEE("eeeeeeeeee"), 
  ;
}
```

Output:
```java
enum MyEnum {
  AAAAAAAA("aaaaaa"),
  BBBBBBBBBBB("bbbbbbbbbb"),
  CCCCCCCCCC("ccccccccc"),
  DDDDDDDDD("ddddddddddddddddddddddddd"),
  EEEEEEE("eeeeeeeeee"), ;
}
```

Expected Output:
```java
enum MyEnum {
  AAAAAAAA("aaaaaa"),
  BBBBBBBBBBB("bbbbbbbbbb"),
  CCCCCCCCCC("ccccccccc"),
  DDDDDDDDD("ddddddddddddddddddddddddd"),
  EEEEEEE("eeeeeeeeee"),
  ;
}
```

**Comment by clementdessoude** [comment]
Hi @natdempk !

Thank you for taking the time to report these issues. I will try to look more deeply into the other ones in the next days.

For this one, I would go with removing the  last comma and the semicolon, as it is similar to what is done in Prettier for TypeScript . The semicolon is already removed since #266 

```ts
// Input
enum Direction {
    Up = 1,
    Down,
    Left,
    Right,
}

// Output
enum Direction {
    Up = 1,
    Down,
    Left,
    Right
}
```

**Comment by jhaber** [comment]
My two cents is that the trailing comma should either always be present or always be stripped (or maybe respect the trailing comma flag). But I don't think it should depend on whether the input code had a trailing comma

**Comment by natdempk** [comment]
👍 I think removing the `,`/`;` entirely is fine, and I agree that the dependency on the comma would be weird, as it technically shouldn't matter either way.

**Comment by andybergon** [comment]
> For this one, I would go with removing the last comma and the semicolon, as it is similar to what is done in Prettier for TypeScript.

Just FYI Prettier 2.0 is out and after long debates they finally decided to [change the default for trailing commas](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-trailingcomma-to-es5-6963httpsgithubcomprettierprettierpull6963-by-fiskerhttpsgithubcomfisker).

**Comment by clementdessoude** [comment]
Haha, I saw that too! The update to Prettier 2.0 will be in the next release, with the default to trailingComma="always"

**Comment by darcatron** [comment]
Hey, glad to see the default to `always`!  Do you have an estimated date for the next release?

**Comment by clementdessoude** [comment]
Probably this weekend. I'd like to wrap a couple of things in it, but I could postpone them for a next release
