### ISSUE TITLE
Long fully qualified names

### ISSUE THREAD

**Issue by andybergon** [jhipster/prettier-java#339]
```java
    com
      .me.very.very.very.very.very.very.very.very.very.very.very.very.very.longg.fully.qualified.name.FullyQualifiedName.builder()
      .build();
```

When a very long Fully Qualified Name is used the first split is used like a class name and the rest is split and indented in another line.

I would expect the FQN to be on one line and the first method call to be on a new one.

```java
    com.me.very.very.very.very.very.very.very.very.very.very.very.very.very.longg.fully.qualified.name.FullyQualifiedName
      .builder()
      .build();
```

**Comment by clementdessoude** [comment]
Hi @andybergon!

For implementing this, I tried to reproduce Prettier's behavior, but I don't understand fully the logic here. If you play with the playground, you can see this:

<img width="1161" alt="Screen Shot 2019-12-30 at 09 41 49" src="https://user-images.githubusercontent.com/25530077/71574396-d3a7f300-2ae8-11ea-84e2-d477d4e8eb94.png">

**Comment by stevegutz** [comment]
@clementdessoude can you please explain your response a little more? It's not clear to me why this was closed. I was about to open a duplicate issue before finding this one.

**Comment by jhaber** [comment]
Agreed, I would expect fully qualified class names to get treated similar to string literals and not line-broken , so something like:
```java
com.me.longg.fully.qualified.name.FullyQualifiedName
  .builder()
  .build();
```

**Comment by clementdessoude** [comment]
It makes also more sense to me. I need to find some time to work on all these issues, but it has been some crazy weeks at work :)
