### ISSUE TITLE
✨ Adding to ast-explorer

### ISSUE THREAD

**Issue by junoatscroll** [jhipster/prettier-java#343]
Just dropping by to say thank you for this project and to let you know I've opened a PR to add this to ASTExplorer in https://github.com/fkling/astexplorer/pull/474 

I've been using this project to write some tooling. When dealing with ASTs for things like eslint rules, I've always found ASTExplorer very helpful. I'm hoping someone finds this useful!

**Comment by clementdessoude** [comment]
Thank you for your feedback! I will follow your issue on astexplorer

**Comment by NilsBaumgartner1994** [comment]
An Ast explorer or method to generate one would be nice, because we too want to modify and work with an ast rather than an cst
