### ISSUE TITLE
Formatting not idempotent with duplicate semicolons

### ISSUE THREAD

**Issue by jhaber** [jhipster/prettier-java#356]
**Prettier-Java 0.6.0**

```sh
# Options (if any):
--color --print-width 90 --no-config --no-editorconfig
```

**Input:** (note the duplicate semicolon)

```java
public class Test {
  public TestField testField;;

  @Override
  public void someMethod() {}
}
```

**Output after first formatting:**

```java
public class Test {
  public TestField testField;
  @Override
  public void someMethod() {}
}
```

**Output after second formatting:**

```java
public class Test {
  public TestField testField;

  @Override
  public void someMethod() {}
}
```

**Expected behavior:**

It seems like the duplicate semicolons in the input cause the first formatting to be slightly off, which requires a second formatting to fix

**Comment by clementdessoude** [comment]
I will have a look

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug and it needs to be fixed

**Comment by jhaber** [comment]
Thanks!
