### ISSUE TITLE
switch case formatting

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/prettier-java#357]
Not sure if it's related to https://github.com/jhipster/prettier-java/issues/276
But I'm opening a new ticket for that, about `switch case`.

**Prettier-Java 0.6.0**

```sh
# Options (if any):
npm run prettier:java
```

**Input:**

```java
    private String formatSwitch(String value) {
        switch (value) {
            case "alpha":
                return "hello";
            case "beta":
                return "morning";
            default:
                return "bye";
        }
    }
```

**Output:**

```java
    private String formatSwitch(String value) {
        switch (value) { case "alpha": return "hello"; case "beta": return "morning"; default: return "bye"; }
    }
```

**Expected behavior:**

I think it shouldn't change, for more visibility.
What do you think @clementdessoude ?

**Comment by clementdessoude** [comment]
Thank you for reporting this! I made a PR that should fix it
