### ISSUE TITLE
.stream() should not wrap

### ISSUE THREAD

**Issue by Shinigami92** [jhipster/prettier-java#363]
We want the `.stream()` method always on the same line as the calling collection.  
All other chained methods should wrap (opinionated if necessary if line is less than `printWidth`)

**Prettier-Java 0.7.0**

```sh
# Options:
--print-width 120 --tab-width 3
```

**Input:**

```java
var grouped = allTheValues.stream().collect(groupingBy(identity(), counting()));

var result = otherValues.stream()
   .map(cachedEntities::entities)
   .map(Set::size)
   .mapToLong(size -> max(1, size))
   .reduce(1, (a, b) -> a * b);
```

**Output:**

```java
var grouped = allTheValues.stream().collect(groupingBy(identity(), counting()));

var result = otherValues
   .stream()
   .map(cachedEntities::entities)
   .map(Set::size)
   .mapToLong(size -> max(1, size))
   .reduce(1, (a, b) -> a * b);
```

**Expected behavior:**

```java
var grouped = allTheValues.stream()
   .collect(groupingBy(identity(), counting()));

var result = otherValues.stream()
   .map(cachedEntities::entities)
   .map(Set::size)
   .mapToLong(size -> max(1, size))
   .reduce(1, (a, b) -> a * b);
```

**Comment by clementdessoude** [comment]
I don't think this is a feature we want to add as it adds too much complexity regarding to the value it adds. 

IMO, it does not arm to have the .stream() on the next line.

That's why I'm closing this issue, but feel free to comment it if you want to continue this discussion!

**Comment by Shinigami92** [comment]
Ok, that's a little bit sad.
Then we will not use this formatter, because it does not meet our needs.
