### ISSUE TITLE
Class Javadoc is ignored

### ISSUE THREAD

**Issue by spuliaiev-sfdc** [jhipster/prettier-java#409]
For the following code the comment for class is missing.
In this java doc there are some important tags located, so they are missing from the class analysis.

```
const javaDocClass = `
package sample.packaged;

import some.Annotation;

/**
 * Example of class
 *
 * @author user.name
 * @since 2020.05.01
 */
@Annotation("Value01")
public class SampleClass extends SuperClass {
  int field01;
}
`;

describe('javaParserSample', function() {
  describe('#parseJavaContent()', function () {
    it('should successfully parse simple Java', function () {
      let parser = require("java-parser");
      let content = parser.parse(javaDocClass);
      assert.equal(content != null, true);
    });
  });
});
```

**Comment by Shaolans** [comment]
Hi, what version of java-parser are you using ?
I ran with the master version and get this https://pastebin.com/vnkAH6gh.
As you can see the javadoc is attached to the typeDeclaration which wraps the class declaration (https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-OrdinaryCompilationUnit).

**Comment by spuliaiev-sfdc** [comment]
"_id": "java-parser@0.8.0",
Thanks! I was expecting to find it in the children collection..
