### ISSUE TITLE
TypeScript support.

### ISSUE THREAD

**Issue by sam-goodwin** [jhipster/prettier-java#416]
Considering this is code for parsing java code into a CST, it would be beneficial to have type definition for the resulting syntax tree.

**Comment by bd82** [comment]
Related to: https://github.com/SAP/chevrotain/issues/851 in the Parsing library.

**Comment by clementdessoude** [comment]
@sam-goodwin I think this issue is closed with #422. Let me know if you think there are some issues/improvements!
