### ISSUE TITLE
Function calls that take a single lambda should not be on a new line

### ISSUE THREAD

**Issue by JaidenAshmore** [jhipster/prettier-java#418]
## Overview

When there is a only a single argument in a function call it seems unnecessary to place it onto a new line. This misaligns with how other prettier languages work, like in Javascript:

**A single argument taking a lambda**

![image](https://user-images.githubusercontent.com/1059637/89757868-d57b6f80-db29-11ea-9b6f-fbc6d08950fc.png)

**When there are multiple arguments, e.g. two lambdas**

![image](https://user-images.githubusercontent.com/1059637/89758035-3014cb80-db2a-11ea-92b7-39a8a48255d3.png)

## Steps to reproduce

**Prettier-Java 0.8.0**

### Stream methods (map, filter, etc)
**Input:**

```java
final List<Integer> values = Stream.of(1, 2)
    .map(n -> {
        // testing method
        return n * 2;
    })
    .collect(Collectors.toList());
```

**Output:**

```java
final List<Integer> values = Stream
    .of(1, 2)
    .map(
        n -> {
            // testing method
            return n * 2;
        }
    )
    .collect(Collectors.toList());
```

**Expected behavior:**

```java
final List<Integer> values = Stream
    .of(1, 2)
    .map(n -> {
        // testing method
        return n * 2;
     })
    .collect(Collectors.toList());
```

### Completable Futures (single argument)

**Input:**

```java
CompletableFuture.supplyAsync(() -> {
    // some processing
    return 2;
});
```

**Output:**

```java
CompletableFuture.supplyAsync(
    () -> {
        // some processing
        return 2;
    }
);
```

**Expected behavior:**

```java
CompletableFuture.supplyAsync(() -> {
    // some processing
    return 2;
});
```

### Completable Future (Multiple Arguments)

**Input:**

```java
CompletableFuture.supplyAsync(() -> {
       // some processing
       return 2;
}, executor);
```

**Output:**

```java
CompletableFuture.supplyAsync(
    () -> {
         // some processing
         return 2;
    },
    executor
);
```

**Expected behavior:**

```java
CompletableFuture.supplyAsync(
    () -> {
        // some processing
        return 2;
     },
     executor
);
```

### Function arguments that exceed width

**Input:**

```java
myFunction((one, two, three, four, five, six) -> {
       // some processing
       return 2;
});
```

**Output:**

```java
myFunction(
      (one, two, three, four, five, six) -> {
           // some processing
           return 2;
      }
);
```

**Expected behavior:**

```java
myFunction(
      (one, two, three, four, five, six) -> {
           // some processing
           return 2;
      }
);
```

**Comment by bsideup** [comment]
I second the suggestion, and it is well aligned with Prettier JS 👍

@clementdessoude we (@AtomicJar) are Bronze sponsors (no bounty access), but would it be possible for us to make a one time donation in addition to it, to set a bounty on this one? Thanks :)

**Comment by jdubois** [comment]
No need for a one time donation, that’s why friends are here 😀
Is this a complex feature? I’m putting $200 but can increase

**Comment by bsideup** [comment]
@jdubois thank you! 💯 😄

Happy to "contribute" by testing (even from PR) and providing early feedback 🙌

**Comment by clementdessoude** [comment]
If I'm not mistaken, I already had a look, and it was not so easy to fix, as the syntax tree is quite complex around lambdas. But it would definitely be better formatted on a single line. I'll try to have a look soon, I may have more inspiration :)

**Comment by jdubois** [comment]
OK, increasing the bounty to $300
