### ISSUE TITLE
prettier-java browser support

### ISSUE THREAD

**Issue by Infinical** [jhipster/prettier-java#419]
Hello,

Id like to use this plugin in a browser based code formatter.I'm experiencing errors related to child process.Kindly create a standalone bundle for use on the browser or please advise on how i can use the plugin for my use case

**Comment by Shaolans** [comment]
Hello,
I think you should check this branch https://github.com/clementdessoude/prettier-java/tree/feat/create-docs-site/website, this is @clementdessoude 's work on a prettier-java playground made in React. It might help you out.

**Comment by Infinical** [comment]
Hi Lingchun

Can you create a standalone module for usage in browser

The php plugin has one
https://github.com/prettier/plugin-php

 Regards
@Infinical

**Comment by madhur** [comment]
This needs to be looked into. I am planning to use this formatter in chrome extension which does not support module. It should expose a .mjs as a browser compatible parser.

**Comment by pascalgrimaud** [comment]
Feel free to start to code if you need this.

As we contribute to Open Source project on our personal time, and we are not paid for that, I don't think it's interesting for us to code this plugin or something that we won't use.

**Comment by AKclown** [comment]
Does it now support formatting in the browser?
