### ISSUE TITLE
Release the build

### ISSUE THREAD

**Issue by GFdevelop** [jhipster/prettier-java#428]
Why you don't release the build on npm registry? I waste time to configure my package to run the build after install and this add a code to maintain to my package...i would like to just add this package with npm install and then use it with the import/require

**Comment by ruddell** [comment]
The packages in this repository are released on the npm registry.  Are you looking for something else?

>## Subpackages
> This project contains 2 packages:
> - [prettier-plugin-java](./packages/prettier-plugin-java) A plugin for [Prettier](https://prettier.io/) to format Java code
>   [![npm-prettier-plugin-java][npm-prettier-plugin-java-image]][npm-prettier-plugin-java-url]
> * [java-parser](./packages/java-parser) A Java Parser using [Chevrotain](https://github.com/SAP/chevrotain) which output a **C**oncrete **S**yntax **T**ree
>  [![npm-java-parser][npm-java-parser-image]][npm-java-parser-url]

https://github.com/jhipster/prettier-java#subpackages

[npm-prettier-plugin-java-image]: https://img.shields.io/npm/v/prettier-plugin-java.svg?color=blue&label=prettier-plugin-java&logo=prettier-plugin-java
[npm-prettier-plugin-java-url]: https://www.npmjs.com/package/prettier-plugin-java
[npm-java-parser-image]: https://img.shields.io/npm/v/java-parser.svg?color=blue&label=java-parser&logo=java-parser
[npm-java-parser-url]: https://www.npmjs.com/package/java-parser

**Comment by ruddell** [comment]
Closing as there was no response for two weeks.
