### ISSUE TITLE
Support preview feature: Pattern Matching for instanceof

### ISSUE THREAD

**Issue by clementdessoude** [jhipster/prettier-java#434]
# Why ?

Patterns instance of are a preview feature from Java 14 & 15. We want to support it because we are hipsters ! 🤘

## Resources:

- https://docs.oracle.com/javase/specs/jls/se15/preview/specs/patterns-instanceof-jls.html
- https://docs.oracle.com/en/java/javase/15/language/pattern-matching-instanceof-operator.html

**Comment by pascalgrimaud** [comment]
@clementdessoude : adding a bounty as it was a lot of work

**Comment by clementdessoude** [comment]
Thanks @pascalgrimaud !! Bounty claimed ! https://opencollective.com/generator-jhipster/expenses/42718 :)

**Comment by clementdessoude** [comment]
I will do a release tomorrow with this :)
