### ISSUE TITLE
Dynamic version of prettier

### ISSUE THREAD

**Issue by xenoterracide** [jhipster/prettier-java#437]
would be good to have the version of prettier depended on be `^2.1.1` or `2.1.x`. I installed prettier first `2.1.2` and then when I went to install this yarn 2 grabbed an additional version of prettier `2.1.1`

**Comment by hc-codersatlas** [comment]
Similar applies for eslint.

**Comment by clementdessoude** [comment]
Hi  @xenoterracide ! I usually don't like using wildcards as it often leads to subtle bugs that can be hard to debug. 

What I can try in the future is to publish a new version of the lib for each of prettier release.

**Comment by clementdessoude** [comment]
I'm closing this, but feel free to comment if you have anything to add
