### ISSUE TITLE
Space before comma in multi-value switch expression case label

### ISSUE THREAD

**Issue by Naveg** [jhipster/prettier-java#439]
**Prettier-Java 1.0.0**

```sh
# Options (if any):
--print-width 80
```

**Input:**

```java
// code snippet
enum TestEnum {
  FOO,
  BAR,
  BAZ,
}

public class Test {

  public void test(TestEnum testEnum) {
    switch (testEnum) {
      case FOO -> System.out.println("Foo!");
      case BAR, BAZ -> System.out.println("Not Foo!");
    }
  }
}
```

**Output:**

```java
// code snippet
enum TestEnum {
  FOO,
  BAR,
  BAZ,
}

public class Test {

  public void test(TestEnum testEnum) {
    switch (testEnum) {
      case FOO -> System.out.println("Foo!");
      case BAR ,BAZ -> System.out.println("Not Foo!");
    }
  }
}
```

**Expected behavior:**
No changes made. Specifically, `case BAR, BAZ` does not become `case BAR ,BAZ`

**Comment by clementdessoude** [comment]
Oooh ! I definitively missed that... Thank you for reporting this !

It should be good with #440

**Comment by DanielFran** [comment]
@clementdessoude Will you release a new version due to this bug?

**Comment by clementdessoude** [comment]
Yes, I think I will release a patch release. 

Will it cause an issue in jhipster ? I thought the previous one was caused by an issue with Node ?

**Comment by DanielFran** [comment]
We update master a few days ago, so we might need to rollback prior the V7 release

**Comment by clementdessoude** [comment]
I will release it tomorrow I think
