### ISSUE TITLE
Incorrect syntax tree

### ISSUE THREAD

**Issue by y912765390** [jhipster/prettier-java#442]
Hi I'm looking at ast online parsing using our parsing method here. But if the text is wrong halfway through, and the grammar crashes, I wonder if we can make something like ANTlR4 so that this node or its parent node is the wrong node without affecting the generation of the entire other syntax tree

**Comment by bd82** [comment]
Hello. @y912765390 

Yes you can have fault tolerance with [Chevrotain](https://github.com/SAP/chevrotain) based Parsers.
- https://sap.github.io/chevrotain/docs/features/fault_tolerance.html

One point to consider is that this Java Parser uses very advanced lookahead logic
to keep the grammar implementation closely aligned with the official Java specifications.
I am uncertain how this advanced lookedahead logic would interact with the error recovery / fault tolerance capabilities...

Cheers.
Shahar.
