### ISSUE TITLE
Formatting not stable

### ISSUE THREAD

**Issue by MartijnDwars** [jhipster/prettier-java#443]
**Prettier-Java 1.0.1 (through Prettier Maven Plugin 0.12)**

Similar to #368, code needs to be formatted multiple times before it stabilizes.

```sh
# .prettierrc
{
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "proseWrap": "always"
      }
    }
  ],
  "printWidth": 120,
  "semi": true,
  "singleQuote": true,
  "bracketSpacing": true,
  "arrowParens": "always",
  "trailingComma": "none"
}
```

**Input:**

```java
package abc;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Foo {

  public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
    Arrays.asList(// a
    // b
    // c
    // d
    )
  );
}
```

**Output after first run:**

```java
package abc;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Foo {

  public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
    Arrays.asList(// b // a
    // c
    // d
    )
  );
}
```

**Output after second run:**

```java
package abc;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Foo {

  public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
    Arrays.asList(// c // b // a
    // d
    )
  );
}
```

I won't go for the third run; I guess the pattern is clear.

**Expected behavior:**
It is probably not very common to put single-line comments inside a parameter list. Nevertheless, it is valid Java code, so Prettier should be able to format it. Multiple runs of Prettier should not produce different outputs, but Prettier should immediately produce a stable output.

**Comment by clementdessoude** [comment]
Thank you for reporting this! I will try to have a look in the next few days

**Comment by clementdessoude** [comment]
I finally took some time to dig in the issue ! Sorry for the delay @MartijnDwars ! 

I opened a PR that should hopefully should fix the issue
