### ISSUE TITLE
decorator on inner class hosed

### ISSUE THREAD

**Issue by xenoterracide** [jhipster/prettier-java#444]
I have this code

```java
void process(
    Map.@NonNull Entry<String, SkeletonConfiguration> entry,
    @NonNull Map<String, Object> context
  ) {
```

but prettier java is turning it into this.
```java
void process(
    Map.@NonNullEntry<String, SkeletonConfiguration> entry,
    @NonNull Map<String, Object> context
  ) {
```

**Comment by clementdessoude** [comment]
Thank you for reporting this, I will try to take a look at it this week

**Comment by clementdessoude** [comment]
Hi @xenoterracide  !

I definitively took longer than a week to deep dive in the issue, sorry for the delay 😕

I opened up a PR that should fix it. If everything is ok, I will merge it and release a new version of the lib
