### ISSUE TITLE
Import sorting doesn't seem compatible with Intellij

### ISSUE THREAD

**Issue by xenoterracide** [jhipster/prettier-java#447]
Intellij IDEA, a very popular java IDE, with very customizable rules, doesn't seem to be able to sort in the same way that prettier-java does. I tried removing all the rules but "everything else" but it didn't work. the reason I mention this is that immediately after commit when reformatting and optimizing commits, intellij effectively reverts the changes by intellij-java. So prettier would have to reformat the files again every time.

If it is possible could you document it? if not maybe go through the possible sort rules for the popular java IDE's and find a common ground that works (IDEA, Eclipse, Netbeans, JDeveloper, VSCode)  come to mind.

**Comment by jhaber** [comment]
I believe this layout should make IntelliJ agree with prettier-java:
![image](https://user-images.githubusercontent.com/611459/102403316-17bf2c80-3fb4-11eb-983f-259a9fcc1667.png)

**Comment by gmarziou** [comment]
Alternatively, you could set `--skip-commit-hook` option when generating your project to skip adding husky commit hooks that run Prettier.

**Comment by pascalgrimaud** [comment]
@xenoterracide : can you have a look at my comment ? https://github.com/jhipster/prettier-java/issues/201#issuecomment-625710921

**Comment by xenoterracide** [comment]
hmm, doesn't seem like that would fix it, as IIRC it was mixing `java.*` in with the other imports. I will give this stuff a try though, I might not get to it until after #444 is fixed.

**Comment by jhaber** [comment]
For what it's worth, we have ~500 engineers using Prettier + IntelliJ without issue using the layout I posted

**Comment by pascalgrimaud** [comment]
What I did for my project is to use prettier plugin for intellij, and replaced the default shortcut to use prettier format
It works so well :-)
