### ISSUE TITLE
Supply a copy/pasteable checkstyle config

### ISSUE THREAD

**Issue by xenoterracide** [jhipster/prettier-java#449]
I wouldn't personally care how this is provided, a file in the repo, or in the readme, but it'd be great to have a copy-pasteable version to start with.  Might also consider asking checkstyle itself to put it on their site with the sun and google ones. can't test contribute atm due to #444 .

Side comment, and I doubt you're willing to fix this, and checkstyle has an autofix issue tracked... but it would be super duper cool if prettier could read the checkstyle config and use its stye rules instead.

**Comment by clementdessoude** [comment]
Hi @xenoterracide ! It's been a while, but I finally took the time to add some docs and a copy/pastable config in #477 !

It is mostly based on the Google style guide, and should be fully compatible with Prettier. Hope it helps :)
