### ISSUE TITLE
Formatter produces uncompilable code

### ISSUE THREAD

**Issue by pulse00** [jhipster/prettier-java#453]
I've created a sample repo which demonstrates the use case [here](https://github.com/pulse00/prettier-java-bug).

* [First commit](https://github.com/pulse00/prettier-java-bug/commit/581b2ca910345af8d6c203c3508e7976707ff91e#diff-3318c59ec33c5c95f2001ad2315b55ac6260debf379b92c2b5ee8c628d199a0d) compiles fine (unformatted)
* [Second commit ](https://github.com/pulse00/prettier-java-bug/commit/db202f2648fb50b6016bfe608f08c65318a0134e)(formatted using `mvn prettier:write`) produces code which does not compile

Unformatted, valid java code (java 8)

```java
SomeClass.@Valid SomeInnerClass someInnerClass = someClass.getInteractions().get(0);
```

prettier-java formats it to code which does not compile:

```java
    SomeClass.@ValidSomeInnerClass someInnerClass = someClass
      .getInteractions()
      .get(0);
```

**Comment by clementdessoude** [comment]
Hi @pulse00 !

Thank you for reporting the issue, and sorry for the delay in response. I opened a PR that should fix the bug. 

If everything is ok, I will merge it and release a new version of the lib

**Comment by pulse00** [comment]
@clementdessoude thanks a lot !
