### ISSUE TITLE
Enum value wrong when value is negative number

### ISSUE THREAD

**Issue by Balabili** [jhipster/prettier-java#463]
**java-parser 1.0.2**

**Input:**

```java
  public enum RequestActionEnum {
    UN_DEFINED(-1),
    ;
    
    private final Integer value;

    RequestActionEnum(Integer value) {
      this.value = value;
    }
  
    public Integer getValue() {
      return value;
    }
  }

```

**Expected behavior:**

value expect -1 but get 1

**Comment by Shaolans** [comment]
I ran your code snipped with prettier-java however I cannot reproduce your issue
this is what I get:
```
public enum RequestActionEnum {
  UN_DEFINED(-1);

  private final Integer value;

  RequestActionEnum(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }
}

```

**Comment by Balabili** [comment]
I wrote a reproduce code in [Codepen](https://codepen.io/balabili/pen/XWMRXqL?editors=1111).

**Comment by Shaolans** [comment]
Hello,
This is working as intended, [this](https://pastebin.com/W0VPh7t6) is an unaryExpression with 2 children: UnaryPrefixOperator containing the '-' and a Primary containing the value '1'.
UnaryPrefixOperator is a category of tokens that is allowed in certain case, you can check it here https://docs.oracle.com/javase/specs/jls/se16/html/jls-15.html#jls-UnaryExpression
