### ISSUE TITLE
Support removing unused imports

### ISSUE THREAD

**Issue by tomereli** [jhipster/prettier-java#468]
Please add an option to auto-remove unused imports instead of just re-organizing them.
The fact is that the IDE (vscode) automatically adds imports when they are used (I guess its the java extension), then the plugin sorts them - but it would be great if it could also delete whatever is unused. We don't want to use the IDE for that because we use prettier checks in maven build in the CI.

**Prettier-Java 0.5.1**

```sh
# Options (if any):
--print-width 80
```

**Input:**

```java
// code snippet
package com.example;

import com.fasterxml.jackson.databind.annotation.JsonAppend;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class test {}

```

**Output:**

```java
// code snippet
package com.example;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonAppend;

public class test {}
```

**Expected behavior:**

All unused imports should be deleted, not organized.

**Comment by bd82** [comment]
TBH this sounds beyond the scope of a formatter and more in the scope of a linter

**Comment by murdos** [comment]
@tomereli : you can use [Spotless ](https://github.com/diffplug/spotless/tree/main/plugin-maven)to combine formatting with prettier-java and automatic removal of unused imports:
```xml
<configuration>
  <java>
    <removeUnusedImports />
    <prettier>
       <!-- see documentation -->
    </prettier>
  </java>
</configuration>
```

**Comment by tomereli** [comment]
> @tomereli : you can use [Spotless ](https://github.com/diffplug/spotless/tree/main/plugin-maven)to combine formatting with prettier-java and automatic removal of unused imports:
> 
> ```
> <configuration>
>   <java>
>     <removeUnusedImports />
>     <prettier>
>        
>     </prettier>
>   </java>
> </configuration>
> ```

Thank you for the suggestion - I was just hoping for something with both IDE integration and Maven support. For everything else we just use prettier along with the prettier java plugin, then we get a seamless experience - we use auto-format on save, and in the CI we run the check using maven.

**Comment by Shaolans** [comment]
Unfortunately as @bd82 this is beyond the scope of prettier-java and is more the role of a linter since we do have to analyze the code to determine if a import is used or not.
I will be closing this issue.
