### ISSUE TITLE
Records support

### ISSUE THREAD

**Issue by DamnClin** [jhipster/prettier-java#473]
The `1.1.0` was released to have Java 14 `record` support but some cases are still not working.

# Records with constructors

When you are overriding the default constructor, ex:

```java
record Issuer(OrganisationName name) {

  public Issuer(String name) {
    this(new OrganisationName(name));
  }
}
```

You get an error:

```sh
[...]Issuer.java: Error: Sad sad panda, parsing errors detected in line: 5, column: 16!
[error] Expecting --> '{' <-- but found --> '(' <--!
[error] 	->compilationUnit
[error] 	->ordinaryCompilationUnit
[error] 	->typeDeclaration
[error] 	->classDeclaration
[error] 	->recordDeclaration
[error] 	->recordBody
[error] 	->recordBodyDeclaration
[error] 	->compactConstructorDeclaration
[error] 	->constructorBody
```
_I get the same error if I keep the same types in the constructor_

# Generic inner records

Sometimes you want to add generics to records defined in a class:

```java
public class State<S, T> {
  // ...

  public static record Result<S, T> (S updated, T result) {
  }
}
```

Formatting will give you this kind of error:

```sh
[...]State.java: Error: Sad sad panda, parsing errors detected in line: 39, column: 30!
[error] Expecting --> ';' <-- but found --> '<' <--!
[error] 	->compilationUnit
[error] 	->ordinaryCompilationUnit
[error] 	->typeDeclaration
[error] 	->classDeclaration
[error] 	->normalClassDeclaration
[error] 	->classBody
[error] 	->classBodyDeclaration
[error] 	->classMemberDeclaration
[error] 	->fieldDeclaration
```

**Comment by Shaolans** [comment]
Hello @DamnClin, thank you for reporting the issue.
This should be fixed, the issue was referenced in https://github.com/jhipster/prettier-java/issues/469.
@pascalgrimaud Maybe we should release a 1.1.1 ? I cannot do it myself since do not have the right to release npmjs

**Comment by pascalgrimaud** [comment]
Ok will try to do a release very soon :-)

**Comment by DamnClin** [comment]
Tested with this morning release, working, thanks
