### ISSUE TITLE
Generic constructor's '>' should be followed by whitespace

### ISSUE THREAD

**Issue by jtkiesel** [jhipster/prettier-java#484]
**Prettier-Java 1.2.0**

**Input:**

```java
public <T> GenericConstructor(T genericParameter) {}
```

**Output:**

```java
public <T>GenericConstructor(T genericParameter) {}
```

**Expected behavior:**

```java
public <T> GenericConstructor(T genericParameter) {}
```

I expect there to be whitespace between the `>` and the constructor name. The provided [Checkstyle rules](https://github.com/jhipster/prettier-java/blob/bc0abb3/docs/checkstyle/checkstyle.xml) also (rightfully) complain about the output, giving me the error message:

> GenericWhitespace '>' should followed by whitespace.

**Comment by clementdessoude** [comment]
Thank you for reporting this ! It should be good with #485

**Comment by clementdessoude** [comment]
@jtkiesel a new version of prettier-plugin-java was released this afternoon with the fix, so it should be good now !
