### ISSUE TITLE
Default interface methods

### ISSUE THREAD

**Issue by sadiqhabib** [jhipster/prettier-java#488]
**Prettier-Java 0.5.1**

```sh
# Options (if any):
```

**Input:**

```java
public abstract class Calculator {
    public interface ISum {
        default int sum(int a, int b) { return a + b; }
    }
}

```

**Error:**

```
SyntaxError: Expected "/*", "//", ";", "<", "@", "abstract", "boolean", "byte", "char", "class", "double", "enum", "final", "float", "int", "interface", "long", "native", "private", "protected", "public", "short", "static", "strictfp", "synchronized", "transient", "void", "volatile", "}" or [ \t\r\n\u000C] but "d" found.

```

**Expected behavior:**
No error :-)

**Comment by clementdessoude** [comment]
Hi @sadiqhabib. 

Thank you for reporting this, but I cannot manage to reproduce this, either on the latest version or with the version v0.5.1 you provide.

I tried to reproduce with the code in this repo: https://github.com/clementdessoude/prettier-java-demo

Can you try to clone it and run:

```bash
npm install

npm run prettier
```

I'm closing the issue, but feel free to comment if you still face the issue :)
