### ISSUE TITLE
prettier-ignore not working as expected

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/prettier-java#505]
`// prettier-ignore` seems not working as expected, unless I don't know how to use it.
If I use `// @formatter:off` and `// @formatter:on`, it works well.

**Prettier-Java 1.4.0**

**Input:**

```java
package tech.jhipster;

import java.util.Map;

public class StrangePrettierIgnore {

  private StrangePrettierIgnore() {}

  public static void drinkBeers() {
    // prettier-ignore
    Map<String, String> beers = Map.of(
      "beer1", "Gulden Draak",
      "beer2", "Piraat",
      "beer3", "Kapittel"
    );

           System.out.println(beers); // not well formated here
  }
}
```

**Output:**

```java
package tech.jhipster;

import java.util.Map;

public class StrangePrettierIgnore {

  private StrangePrettierIgnore() {}

  public static void drinkBeers() {
    // prettier-ignore
    Map<String, String> beers = Map.of(
      "beer1", "Gulden Draak",
      "beer2", "Piraat",
      "beer3", "Kapittel"
    );

           System.out.println(beers); // not well formated here
  }
}
```

**Expected behavior:**

```java
package tech.jhipster;

import java.util.Map;

public class StrangePrettierIgnore {

  private StrangePrettierIgnore() {}

  public static void drinkBeers() {
    // prettier-ignore
    Map<String, String> beers = Map.of(
      "beer1", "Gulden Draak",
      "beer2", "Piraat",
      "beer3", "Kapittel"
    );

    System.out.println(beers); // not well formated here
  }
}
```

**Comment by clementdessoude** [comment]
Oh indeed ! I'll have a look

**Comment by pascalgrimaud** [comment]
Thanks for the confirmation.
Adding a bounty as it's a bug, and because this project is so nice. It deserved more contributions :)

**Comment by somayaj** [comment]
Hi, I tried this version of the plugin   

<plugin>
                <groupId>com.hubspot.maven.plugins</groupId>
                <artifactId>prettier-maven-plugin</artifactId>
                
                <version>0.8</version>
            </plugin>

case 1: without //prettier-ignore 

package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        var string = "";
        SpringApplication.run(DemoApplication.class, args);
                System.out.println("tesitng");
    }
}

was formatted to: as expected. 
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        var string = "";
        SpringApplication.run(DemoApplication.class, args);
        System.out.println("tesitng");
    }
}
Case 2: with //prettier-ignore it was ignored as expected. 

package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//prettier-ignore
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        var string = "";
        SpringApplication.run(DemoApplication.class, args);
                    System.out.println("tesitng");
    }
}

is there a defect at all? maybe I'm missing something here?

Asha

**Comment by somayaj** [comment]
any update here?

**Comment by jtkiesel** [comment]
@pascalgrimaud Bounty claimed: https://opencollective.com/generator-jhipster/expenses/171756

**Comment by pascalgrimaud** [comment]
@jtkiesel : approved, thanks for your work
