### ISSUE TITLE
Record parameters being forced to a single line

### ISSUE THREAD

**Issue by matthewswitzer** [jhipster/prettier-java#507]
**Prettier-Java 1.4.0**

**Input:**

```java
public record Person(
    String firstName,
    String lastName,
    String email,
    String phoneNumber,
    String streetAddress,
    String city,
    String state,
    String zipCode
) {}

```

**Output:**

```java
public record Person(
    String firstName, String lastName, String email, String phoneNumber, String streetAddress, String city, String state, String zipCode
) {}

```

**Expected behavior:**

Long lists of parameters should remain on separate lines.

**Comment by clementdessoude** [comment]
Hi @matthewswitzer ! Thanks for reporting this ! 👍 

It is indeed something we missed. I opened a PR that should fix the issus !

**Comment by pascalgrimaud** [comment]
Adding a bounty to improve this part

**Comment by clementdessoude** [comment]
Thanks @pascalgrimaud ! Bounty claimed :)

https://opencollective.com/generator-jhipster/expenses/52847
