### ISSUE TITLE
Support preview feature: Pattern Matching for switch

### ISSUE THREAD

**Issue by trushev** [jhipster/prettier-java#510]
Patterns in switch are preview feature from Java 17. Can it be supported?:)
https://openjdk.java.net/jeps/406

Currently, sad sad panda is thrown from the following code snippet
```java
static String formatterPatternSwitch(Object o) {
    return switch (o) {
        case Integer i -> String.format("int %d", i);
        case Long l    -> String.format("long %d", l);
        case Double d  -> String.format("double %f", d);
        case String s  -> String.format("String %s", s);
        default        -> o.toString();
    };
}
```

**Comment by clementdessoude** [comment]
Hi @trushev !

I started the work to support this new feature. I think it is almost done but needs to add a few tests to check everything works as expected :)

**Comment by trushev** [comment]
@clementdessoude 
Wow, I'm surprised by such a quick implementation, thank you:)

**Comment by pascalgrimaud** [comment]
Adding a bounty on this
