### ISSUE TITLE
Casting not handled properly results in compile-time error

### ISSUE THREAD

**Issue by Robinsstudio** [jhipster/prettier-java#517]
Hello here! :)

I'm currently having a formatting issue with Prettier which makes my Java code incorrect.
When casting a variable to a type such as `(A & B)`, Prettier transforms it into `(A) & B` which is invalid.
Here is a simple example:

**Prettier-Java 1.5.0**

**Input:**

```java
public class PrettierIssue {

    class A {}

    interface B {}

    public <T extends A & B> foo(T bar) {}

    public static void main(String[] args) {
        Object obj = new Object();
        foo((A & B) obj);
    }

}
```

The above code is turned into:

**Output:**

```java
public class PrettierIssue {

  class A {}

  interface B {}

  public <T extends A & B> foo(T bar) {}

  public static void main(String[] args) {
    Object obj = new Object();
    foo((A) & B obj);
  }
}
```

It would be sooo nice if this could be addressed as this is an issue that I have in a corporate project. Thank you! 🙏

**Comment by clementdessoude** [comment]
Hi @Robinsstudio ! Thank you for reporting this ! 

#518 should fix the issue :)

**Comment by Robinsstudio** [comment]
Wow! Thank you for the very quick response! 😃
