### ISSUE TITLE
Force wrap of method chains

### ISSUE THREAD

**Issue by JanecekPetr** [jhipster/prettier-java#531]
**Prettier-Java 1.6.1**

```sh
# Options (if any):
--print-width 140
```

**Input:**

```java
return Arrays.stream(directories)
		.filter(dir -> !dir.isBlank())
		.collect(Collectors.toList());
```

**Output:**

```java
return Arrays.stream(directories).filter(dir -> !dir.isBlank()).collect(Collectors.toList());
```

**Expected behavior:**
```java
return Arrays
    .stream(directories)
    .filter(dir -> !dir.isBlank())
    .collect(Collectors.toList());
```

or (not the point here)

```java
return Arrays.stream(directories)
    .filter(dir -> !dir.isBlank())
    .collect(Collectors.toList());
``` 

I understand we can tweak the print width, but this is about the general idea of forcing chained methods to be wrapped every time as every method is a separate step, and should be on a separate line. One line - one idea, one action.

Obviously the authors think short chained methods can be on a single line, and that's fine. I'm here to try and weigh the opinion in the other side if possible.

(I'm sure somebody already reported this ages ago, but I could not find a duplicate, sorry.)

**Comment by clementdessoude** [comment]
Hi @JanecekPetr !

Thank you for this proposal, and sorry to only answer now !

The issue here is to have a heuristic where to break, and it is extremely difficult. For instance, you have a line break between Arrays and stream, but not between Collectors and toList. 

We try to follow prettier's behaviour on this topic

**Comment by JanecekPetr** [comment]
I'd happily forgo the split between Arrays and stream as well (as Google Style Format does), but that's not the point here, nor is it important.

A break between Collectors and toList is also a non-issue as that's a single method call, no chain. It's one nested expression. Now, if that were `Collectors.extra().crispy()`, I'd consider breaking there.

But this is about chained method calls. And I have not seen a single case where multiple chained method calls on a single line were better than separated. You could make an argument for things like `someFactory.create().run()`, but I wouldn't, and would split it anyway. If we can split them when they're long, we can for sure split them when they're short, too.

**Comment by jhaber** [comment]
If you set your print width to 70 or something you should get pretty close to your desired behavior. But what your asking for is a pretty big departure from the current behavior. I believe prettier-js has had discussions on this topic without really going anywhere:
https://github.com/prettier/prettier/issues/1565

The current behavior seems to be not forcing the wrapping of call chains unless the print width is exceeded, for example:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAdAIwBQEp1h7oAmRcRAZniADQgQAOMAltAM7KioBO3EA7gAUeCDilQAbfqgCeHOpm6owAazgwAyqgC2cADLMocZBUls4CpavUaGywwHNkMbgFcLIONsxxixX3qoUA6uqA5wAGIQ3NqoMCzByGiuMBC0IAAWMNoSAOoZzPBsdmBwGqKFzABuhTJJYGzyIIbm3DCCSg6xJmYeAFZsAB4ajhJwAIquEPA9EuZ0dtytSZioPhLpDNyGMLnMxDAZyAAcAAwLfOa5SgxJW3CtVcZ0AI5T8B2MYmhsALRGvl86W4cDezBBHTC3SQpjmHnM2mYzjc8NGE3exhhvToMDWewORyQACYcUpmBJHABhCDaaGeNgAVnSrnMABU1mJYfMQFV3ABJKD+WAaMDbJgAQUFGhgMjGs3MAF8FUA

It sounds like you might be better suited by a more configurable code formatter, that lets you tweak the output based on your preferences

**Comment by JanecekPetr** [comment]
That's fair, I'm happy with this assessment. The issue originated from me looking at a piece of code I _personally_ thought was suboptimal and not up to modern Java standards. Obviously it's not a big deal, and I see I may be the minority here.

Thank you!
