### ISSUE TITLE
strict mode: Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by lisonge** [jhipster/prettier-java#547]
<https://github.com/jhipster/prettier-java/blob/main/packages/java-parser/src/utils.js>

```js
"use strict";

function getSkipValidations() {
  return (
    (process && // (not every runtime has a global `process` object
      process.env &&
      process.env["prettier-java-development-mode"] === "enabled") === false
  );
}

module.exports = {
  getSkipValidations
};
```

in browser env and `strict mode`, will throw error

![image](https://user-images.githubusercontent.com/38517192/186062804-296f588c-b2fb-45fb-90e4-f4e946473e9d.png)

you can fix it by `globalThis.process = globalThis.process`
```js
"use strict";
globalThis.process = globalThis.process;
function getSkipValidations() {
  return (
    (process && // (not every runtime has a global `process` object
      process.env &&
      process.env["prettier-java-development-mode"] === "enabled") === false
  );
}

module.exports = {
  getSkipValidations
};
```

**Comment by lisonge** [comment]
`prettier-plugin-java/v1.6.2.umd.js` com form <https://github.com/lisonge/pkg-cdn.git>

**Comment by lisonge** [comment]
fix by custom rollup plugin

```json5
      {
        name: 'fix_process',
        transform(code, id) {
          if (
            id.endsWith('/node_modules/java-parser/src/utils.js') &&
            code.includes('process')
          ) {
            return {
              code: [code, ';globalThis.process = globalThis.process;'].join(
                '\n'
              ),
              map: null,
            };
          }
          return;
        },
      }
```

**Comment by mazhe-nerd** [comment]
> https://github.com/jhipster/prettier-java/blob/main/packages/java-parser/src/utils.js
> 
> ```js
> "use strict";
> 
> function getSkipValidations() {
>   return (
>     (process && // (not every runtime has a global `process` object
>       process.env &&
>       process.env["prettier-java-development-mode"] === "enabled") === false
>   );
> }
> 
> module.exports = {
>   getSkipValidations
> };
> ```
> 
> in browser env and `strict mode`, will throw error
> 
> ![image](https://user-images.githubusercontent.com/38517192/186062804-296f588c-b2fb-45fb-90e4-f4e946473e9d.png)
> 
> you can fix it by `globalThis.process = globalThis.process`
> 
> ```js
> "use strict";
> globalThis.process = globalThis.process;
> function getSkipValidations() {
>   return (
>     (process && // (not every runtime has a global `process` object
>       process.env &&
>       process.env["prettier-java-development-mode"] === "enabled") === false
>   );
> }
> 
> module.exports = {
>   getSkipValidations
> };
> ```

globalThis.process = globalThis.process可以修复的原理是？

**Comment by mazhe-nerd** [comment]
@lisonge globalThis.process = globalThis.process 可以修复的原理是？

**Comment by lisonge** [comment]
> @lisonge globalThis.process = globalThis.process 可以修复的原理是？

浏览器环境没有 `process` 全局变量/属性，`严格模式` 下使用未声明的变量/属性会报未定义错误

<https://github.com/jhipster/prettier-java/blob/d7b64304a951320139d13ab856963a28b96c4aac/packages/java-parser/src/utils.js#L13-L15>

`globalThis.process = globalThis.process` 的意思是声明 `process` 为全局变量/属性，让 `process` 变成已定义，此时再在函数内使用 `process` 则不会报未定义错误

**Comment by NilsBaumgartner1994** [comment]
Having the same issue here
