### ISSUE TITLE
type annotations on fields

### ISSUE THREAD

**Issue by xenoterracide** [jhipster/prettier-java#548]
```
❯ yarn why prettier-plugin-java
└─ backend@workspace:.
   └─ prettier-plugin-java@npm:1.6.2 (via npm:^1.6.2)
```

```sh
# Options (if any):
--print-width 80
```

**Input:**

```java
  private @Nullable Long id;
```

**Output:**

```java
  @Nullable
  private  Long id;
```

**Expected behavior:**

Although this works, it is incorrect, it's supposed to go on the type. I'm not sure how best for you to deal with this. Perhaps you could sort annotations but not move them when they're in that position? I notice it's not moving them when they're on methods.

```
    (see https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations)
  Did you mean to remove this line?
/Users/nqy642/IdeaProjects/iw-pm-backend/module/controller/transactional/src/main/java/com/xenoterracide/ppm/transactional/domainmodel/entities/ExceptionEntity.java:91: error: [AnnotationPosition] @Nullable is a TYPE_USE annotation, so should appear after modifiers and directly before the type.
    private Long creatorId;
```

**Comment by jhaber** [comment]
Is this a duplicate of https://github.com/jhipster/prettier-java/issues/525 ?

**Comment by xenoterracide** [comment]
haha, yes, obviously you haven't fixed it yet ;) sometimes I forget when I report things and they aren't fixed and they come back to annoy me again. You still need to fix it ;) .

**Comment by xenoterracide** [comment]
also since it didn't affect methods I thought maybe it was partially fixed
