### ISSUE TITLE
Configure `prettier --write` to run with Custom Checkstyle

### ISSUE THREAD

**Issue by Namyalg** [jhipster/prettier-java#555]
Is there a way to pass a custom checkstyle file to the command `prettier --write` ?

**Comment by jtkiesel** [comment]
Prettier cannot use a Checkstyle file for configuration. For information on how to configure Prettier, see their docs here: https://prettier.io/docs/en/configuration

@pascalgrimaud I recommend closing this issue.

**Comment by pascalgrimaud** [comment]
Thanks @jtkiesel
