### ISSUE TITLE
"Contributing" guide is not clear

### ISSUE THREAD

**Issue by mernst** [jhipster/prettier-java#556]
https://github.com/jhipster/prettier-java/blob/main/CONTRIBUTING.md says:

> To get up and running, install the dependencies and run the tests:
> 
> ```
> yarn
> yarn test
> ```

So I did this:

```
git clone https://github.com/jhipster/prettier-java.git
cd prettier-java
yarn
```

The output of the `yarn` command was

```
ERROR: There are no scenarios; must have at least one.
```

What am I missing?

**Comment by clementdessoude** [comment]
Hello mernst ! You may have the wrong yarn package :) 

https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

I'm closing the issue, as it seems this is the fix to your issue, but feel free to comment if it does not !

If you need some guidance to start contributing, you can also comment on this issue

**Comment by mernst** [comment]
Thank you for the explanation.  I appreciate it.

Since the wrong yarn is installed by default on Ubuntu, I suggest adding a warning to https://github.com/jhipster/prettier-java/blob/main/CONTRIBUTING.md, or saying what to do if the "ERROR: There are no scenarios; must have at least one." error appears.  Thanks.
