### ISSUE TITLE
Migrate to Prettier v3

### ISSUE THREAD

**Issue by sosukesuzuki** [jhipster/prettier-java#557]
Sorry for ignoring the issue template...

Hi, I am a maintainer at Prettier.

The Prettier team is currently working on v3(still alpha).
v3 will include breaking changes to the plugin interface.
Please see https://github.com/prettier/prettier/releases/tag/3.0.0-alpha.2 for more information.

I created this issue to help major plugins migrate to Prettier v3.

Myself and @fisker have created a migration guide which you can see here:

https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

If you have any questions, feel free to mention us. We can help you.

If you have already migrated to Prettier v3, sorry but please close this issue.

**Comment by clementdessoude** [comment]
Hi @sosukesuzuki ! Thank you for your work on Prettier !

I tried this morning to update the plugin to Prettier v3. Everything seems working overall, there are just a few things I need to clean up :)

**Comment by jdubois** [comment]
I put a bug bounty on this as it’s super important and @clementdessoude you always do an awesome job maintaining this!
cc @pascalgrimaud @deepu105

**Comment by pascalgrimaud** [comment]
Totally agree :-)

**Comment by clementdessoude** [comment]
Thanks @jdubois @pascalgrimaud :) 

@sosukesuzuki everything seems to be working fine ! I prepared the migration in #561. I'll keep this issue and #558 opened until Prettier v3 is out !

**Comment by clementdessoude** [comment]
Bounty claimed @pascalgrimaud :) 

https://opencollective.com/generator-jhipster/expenses/148796

**Comment by pascalgrimaud** [comment]
@clementdessoude : approved

**Comment by murdos** [comment]
Closing ticket since https://github.com/jhipster/prettier-java/pull/558 has been merged and v2.2.0 has been released :)
