### ISSUE TITLE
Support for require-pragma option

### ISSUE THREAD

**Issue by yannick-paz** [jhipster/prettier-java#573]
Judging by [this function](https://github.com/jhipster/prettier-java/blob/prettier-plugin-java%402.0.0/packages/prettier-plugin-java/src/index.js#L30), there is currently no support for the [require-pragma](https://prettier.io/docs/en/options.html#require-pragma) Prettier option.
This is an issue for larger codebases where adoption cannot be incremental.
It seems like low-hanging fruit seeing as it's been resolved with a fairly straightforward regex for other languages (see [HTML](https://github.com/prettier/prettier/blob/2.8.3/src/language-html/pragma.js#L3), [YAML](https://github.com/prettier/prettier/blob/2.8.3/src/language-yaml/pragma.js#L7) and [GraphQL](https://github.com/prettier/prettier/blob/2.8.3/src/language-graphql/pragma.js#L3))

**Comment by clementdessoude** [comment]
Closing this issue as @yannick-paz resolved it in #574 :)
