### ISSUE TITLE
Use different indentation level for `throws`

### ISSUE THREAD

**Issue by jsh9** [jhipster/prettier-java#583]
I tried Prettier-java today and saw this formatting result:

```java
public void myMethodWithLongName(final boolean myArg1, ...)
    throws IOException {
    final String myVariable = "123";
    ...
```

This makes the `throws` line and the 1st line of the method body visually indistinguishable.  Is it possible to change this behavior?

I think a potential solution would be: to allow a different indentation level (such as 8) for line break indentations.

**Comment by jhaber** [comment]
I believe this is referred to as a "continuation" indent. Some related discussion: 
https://github.com/jhipster/prettier-java/issues/429
https://github.com/jhipster/prettier-java/pull/384#discussion_r410712022

**Comment by jtkiesel** [comment]
Closing as a duplicate of #429.
