### ISSUE TITLE
Convert logo to SVG (or other lighter format)

### ISSUE THREAD

**Issue by murdos** [jhipster/prettier-java#589]
[Current logos](https://github.com/jhipster/prettier-java/tree/main/logo) are in BMP format, and the light one is displayed on the README.
It would be nice to use an image format that is lighter

**Comment by jtkiesel** [comment]
@murdos I've created #590 which contains a light and dark version of the logo recreated as an SVG. Let me know if you would like any changes made to them. I can also include other logos, such as the "icon" style logo I've attached below.

<img src="https://github.com/jhipster/prettier-java/assets/7101769/f35aeef3-11c5-447d-b64d-8ca892ad9710" width="250">
