### ISSUE TITLE
Indentation issues since 2.3.0

### ISSUE THREAD

**Issue by MLNW** [jhipster/prettier-java#601]
**Prettier-Java 2.3.0**

```sh
{
  "useTabs": false,
  "trailingComma": "none",
  "printWidth": 100,
  "tabWidth": 2,
  "plugins": ["prettier-plugin-java"],
  "overrides": [
    { "files": "*.java", "options": { "tabWidth": 4 } }
  ]
}

```

**Input:**

```java
            fileSystemDetails =
                FileHandlerDetails
                    .builder()
                    .fileSystemType(
                        EntityUtils.update(
                            entity.getFileSystemDetails().getFileSystemType(),
                            update.getFileSystemDetails().getFileSystemType()
                        )
                    )
```

**Output:**

```java
            fileSystemDetails =
            FileHandlerDetails
                .builder()
                .fileSystemType(
                    EntityUtils.update(
                        entity.getFileSystemDetails().getFileSystemType(),
                        update.getFileSystemDetails().getFileSystemType()
                    )
                )
```

**Expected behavior:**

The input should stay the same.

**Workaround:**

Stay on v2.2.0.

**Comment by Magotchi** [comment]
I'm seeing this problem in a lot of code and am remaining on 2.2.0 to work around it.

**Comment by pascalgrimaud** [comment]
Cc @clementdessoude : I'm adding a bounty for having a fix on this

**Comment by jtkiesel** [comment]
This appears to have been caused by #594. I'll begin working on a fix.

**Comment by jtkiesel** [comment]
@clementdessoude @pascalgrimaud We should probably release 2.3.1 with this fix, or else anyone who upgrades to 2.3.0 will experience this issue and likely be forced to downgrade back to 2.2.0.

**Comment by pascalgrimaud** [comment]
Yes, if @clementdessoude is not available to do that, I'll do a release

**Comment by clementdessoude** [comment]
Thanks for the fix @jtkiesel and the review @pascalgrimaud, launching the release right now !

**Comment by pascalgrimaud** [comment]
@jtkiesel : don't forget to claim the bounty here

**Comment by jtkiesel** [comment]
@pascalgrimaud Bounty claimed: https://opencollective.com/generator-jhipster/expenses/159786

**Comment by pascalgrimaud** [comment]
@jtkiesel : approved
