### ISSUE TITLE
Migrate e2e pipeline tests to use Java 17

### ISSUE THREAD

**Issue by DanielFran** [jhipster/prettier-java#609]
For the newest Jhipster 8 version, Java default version is now Java 17.

Following https://github.com/jhipster/prettier-java/pull/588, E2E pipeline testing needs to be update to use Java 17 and may be use Node 18 as minor node version (Node 14 and 16 are deprecated).

**Comment by jtkiesel** [comment]
@DanielFran Bounty claimed: https://opencollective.com/generator-jhipster/expenses/169225

**Comment by DanielFran** [comment]
@jtkiesel approved
