### ISSUE TITLE
Don't split a short line static method to two lines.

### ISSUE THREAD

**Issue by xenoterracide** [jhipster/prettier-java#626]
putting `Try` and `of` on separate lines here seems weird.

**Input:**

```java
    private static <T extends Group> Function<Constructor<?>, T> createInstance(Group entity) {
        return ctor -> Try.of(() -> {
                    @SuppressWarnings("unchecked")
                    var ng = (T) ctor.newInstance(entity.getId(), entity.getSystemGenerated(), entity.getVersionKey());
                    return ng;
                })
                .getOrElseThrow(ex -> new RuntimeException(ex));
    }
```

**Output:**

```java
  private static <T extends Group> Function<Constructor<?>, T> createInstance(Group entity) {
    return ctor ->
      Try
        .of(() -> {
          @SuppressWarnings("unchecked")
          var ng = (T) ctor.newInstance(entity.getId(), entity.getSystemGenerated(), entity.getVersionKey());
          return ng;
        })
        .getOrElseThrow(ex -> new RuntimeException(ex));
  }
```

**Expected behavior:**

```java
  private static <T extends Group> Function<Constructor<?>, T> createInstance(Group entity) {
    return ctor ->
      Try.of(() -> {
          @SuppressWarnings("unchecked")
          var ng = (T) ctor.newInstance(entity.getId(), entity.getSystemGenerated(), entity.getVersionKey());
          return ng;
        })
        .getOrElseThrow(ex -> new RuntimeException(ex));
  }
```

or perhaps even this since the return is implicit.

```java
    return ctor -> Try.of(() -> {
```

**Configuration:**

```json
  "dependencies": {
    "prettier": "^3.1.1",
    "prettier-plugin-java": "^2.5.0"
  }
```

```yaml
printWidth: 120
plugins:
  - prettier-plugin-java
```

```ini
root = true

[*]
trim_trailing_whitespace = true
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 2

[*.bat]
end_of_line = crlf
```

**Comment by jhaber** [comment]
I think it would be weird to have the `.of` not line-broken, but have the `.getOrElseThrow` line-broken later. It seems like prettier and prettier-java both try to follow the philosophy where as soon as one element in an expression get line-broken, then every element gets line-broken (same idea for call chains and method arguments). This avoids any heuristics so you get simple, predictable behavior, it scales up very well to arbitrarily complex nested expressions, and the downside is you end up with a lot of linebreaks

**Comment by jtkiesel** [comment]
I believe the TypeScript equivalent of the input you provided would roughly be:
```ts
class Example {
    private static createInstance<T extends Group>(entity: Group): (ctor: { newInstance: (...args: unknown[]) => unknown }) => T {
        return ctor => Try.of(() => {
                    var ng = ctor.newInstance(entity.getId(), entity.getSystemGenerated(), entity.getVersionKey()) as T;
                    return ng;
                })
                .getOrElseThrow(ex => new RuntimeException(ex));
    }
}
```

Such an input yields the following output from Prettier ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKIAe6AtgA6pw7AA6UO9OpATgJYBu68OmMnLYOMEzic4ASSg90UMHAA8AFRxwC8KABNcAcSYQArqQB8ACgQwWMAJ5IcO-aQCUN42BgQmN4DihwA7hKkZOGcAOjD0JgBzTBs9KABrKAhfKABtAF0HHABeQxw4xOS6AF8s3JwlGjoGGuEYPSY6V3ccvIUmSxCIADNjYzK8qprhkeGOJm9InME3JhCff0leINNYC07IuBgxdX6AGmU1qxDNmABlSx44Yi0EOCZRXYcDs3WTrYA1e8wWaABpOCWfpZLAVADctFGUOGdQadCgkQh1Whw1KkJRw3eMAA8kw8KhMHAFAALXS+UwEVrePw4ABKcXMxDghFkpHM0ApDgcSJqxVoxRAexAEDZv0kyFAETJAAUIghMMgQOg2BAWOpBSAAEYPMDxLZnEhwAAyLB8yG66AJcCF2vQuv1pDtpsiyBgTD01pAhOILFd7s9KlI9xYTNgloU9ygERYcAVSAtVqFPwRFAAinoIPBzZbCUKAFaYAhnZ1pjNZ+M5z0ARzLcGlulIcaVmAAtD44OoOxq3egWKhnQBhCDEYjoRWW1Aa5ORCgAQRgbpYmr08Gl9xNZoriZAxJgxFQAHViRZY47ZGd5RZ2OtFWBsBq2B6JJ3YGchCw2bONGcrBRs9vmAgQkDweUhFWYWN7jYOANVNQkmBget0EiUd-1zEBHSYeDFSsINMHfNkNWEGsWGEJCULHLd0L0QkFHQTU4wTdDrk1DtO3UI1pEiPRkLgAAxdxRwXZ1xxXCBu3og81RgYlkAAFiFZhTRgKT1Bk5AAEYACYAAZimKIA)):
```ts
class Example {
    private static createInstance<T extends Group>(
        entity: Group,
    ): (ctor: { newInstance: (...args: unknown[]) => unknown }) => T {
        return ctor =>
            Try.of(() => {
                var ng = ctor.newInstance(entity.getId(), entity.getSystemGenerated(), entity.getVersionKey()) as T;
                return ng;
            }).getOrElseThrow(ex => new RuntimeException(ex));
    }
}
```

I think an appropriate action item for this issue would be to try to align Prettier Java's formatting of chained method invocations with lambda parameters more closely with Prettier TypeScript's.

**Comment by xenoterracide** [comment]
Yeah that looks closer (If not the same?) As what I said I was expecting.

**Comment by jhaber** [comment]
I think the difference is that the `.getOrElseThrow` isn't line-broken.

**Comment by xenoterracide** [comment]
is this consistent with typescript?

```java
       var result = ImmutableFindCustomerCommand
            .builder()
            .correlationId(UUID.randomUUID().toString())
            .build()
            .apply(customerApi)
            .block();
```

again, I thought that formatter did

```java
       var result = ImmutableFindCustomerCommand.builder()
            .correlationId(UUID.randomUUID().toString())
            .build()
            .apply(customerApi)
            .block();
```

**Comment by xenoterracide** [comment]
Hey, thanks for the good work, I suspect the PR fixed this, but in case it didn't, I figured I'd share it now. Checkstyle alerted me.

https://github.com/xenoterracide/gradle-semver/blob/e2049e72c075ea66cbcc0a1e5ca64820a57399ec/src/main/java/com/xenoterracide/gradle/semver/SemVerPlugin.java#L54-L59
