### ISSUE TITLE
Auto formatting on save using maven-plugin-java?

### ISSUE THREAD

**Issue by jaoxford** [jhipster/prettier-java#674]
Just curious if there's a way of formatting this on save? I am using intelliJ. 
I have tried to use the file-watcher plugin, with the following config for my IDE:

<img width="747" alt="Screenshot 2024-06-20 at 15 11 19" src="https://github.com/HubSpot/prettier-maven-plugin/assets/26263928/89f297f1-636e-4d98-8f74-ccbd3acf9516">

When I save my file I get the following error:

```
//.m2/repository/com/hubspot/maven/plugins/prettier-maven-plugin/0.16/prettier-maven-plugin-0.16-prettier-java-0.7.0/prettier-java/node_modules/prettier/bin-prettier.js --write src/main/java/MyFile.java
[error] No matching files. Patterns tried: src/main/javaMyFile.java !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

Process finished with exit code 2
```

Here's the output of print-args:

```
printWidth=90
tabWidth=4
useTabs=false
noConfig=true
noEditorconfig=true
inputGlob=src/main/java/**/*.java
inputGlob=src/test/java/**/*.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.273 s
[INFO] Finished at: 2024-06-20T15:15:03+01:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

And if I manually trigger prettier:write that is also fine. Ideally this would be something that runs on every save, so I don't have to think about it!

Any idea or help would be appreciated!

**Comment by murdos** [comment]
I'm not using maven-plugin-java, but it works fine for me using `Actions on Save`:
![image](https://github.com/jhipster/prettier-java/assets/155828/c72ea54f-8fe8-409b-80a4-e4855e224e80)

Don't forget to add the java extension to files that should be prettified:
![image](https://github.com/jhipster/prettier-java/assets/155828/1924087d-c290-4e7f-a4df-8fa95119f344)

Maybe you can try the manual Prettier configuration above to fill the exact prettier location?

**Comment by jaoxford** [comment]
I can run the file watcher on save, like so:

<img width="1096" alt="Screenshot 2024-06-21 at 12 43 42" src="https://github.com/jhipster/prettier-java/assets/26263928/2681a0c5-b90c-418f-a16a-47cfa82b02e1">

However, I still get the same prettier error I listed above.

**Comment by jaoxford** [comment]
Got working, I had to force it to write to Java files: `--write $FilePathRelativeToProjectRoot$ "**/*.java`
