### ISSUE TITLE
New version when?

### ISSUE THREAD

**Issue by DashwoodIce9** [jhipster/prettier-java#675]
Last version (2.6.0) was released 4 months ago and I can't upgrade to it since there's [this regression](https://github.com/jhipster/prettier-java/issues/650) introduced with it. Requesting release of v2.7.0 with the fix for this (it's already merged). It's annoying having to run `npm outdated` and seeing `prettier-java` flagged there.

**Comment by jtkiesel** [comment]
Thank you for creating this issue! The role of primary maintainer of this project is currently being transferred to myself, and I am working on getting the proper permissions to publish `java-parser@2.3.1` and `prettier-plugin-java@2.6.1` to npm. I will report back here as soon as they are published, which I hope will be within the next couple of days. Thank you for your patience!

@DanielFran / @pascalgrimaud: If either of you is able to help with this by making me ([jkiesel](https://www.npmjs.com/~jtkiesel)) a collaborator on the [java-parser](https://www.npmjs.com/package/java-parser) and [prettier-plugin-java](https://www.npmjs.com/package/prettier-plugin-java) npm projects such that I can publish these new versions, that would be greatly appreciated!

**Comment by pascalgrimaud** [comment]
I'll have a look this morning :-)

**Comment by pascalgrimaud** [comment]
it should be ok, @jtkiesel
don't hesitate to ping me if it is not

**Comment by jtkiesel** [comment]
Thank you, @pascalgrimaud!

@DashwoodIce9: I've just published `java-parser@2.3.1` and `prettier-plugin-java@2.6.1` to npm. Thank you for your patience!
