### ISSUE TITLE
Doesn't work under yarn pnp

### ISSUE THREAD

**Issue by leaumar** [jhipster/prettier-java#677]
For a long time we've been trying to make this plugin work under yarn 4 with [pnp](https://yarnpkg.com/features/pnp) enabled (instead of `node-modules`), but every time we try to run it, we get this error:

```
> yarn format
[error] Cannot find package 'prettier-plugin-java' imported from C:\Users\***\Projects\***\noop.js
```

This seems to be a matter of setting up the right details in this plugin's package.json, rather than something the plugin user needs to do, but I don't know the details of all that. We don't have this issue with other node dependencies or even other prettier plugins. Could you please look into supporting yarn pnp? It shouldn't require you to make any actual changes, just set some manifest fields probably. Thanks

partial package.json
```json
{
    "scripts": {
        "format": "prettier . --write --list-different --ignore-unknown --ignore-path .gitignore !yarn.lock !.yarn"
    },
    "devDependencies": {
        "@prettier/plugin-xml": "3.4.1",
        "prettier": "^3.2.5",
        "prettier-plugin-java": "2.6.4"
    },
    "packageManager": "yarn@4.3.1",
    "engines": {
        "node": "20.11.1"
    }
}
```

yarnrc.yml
```yml
compressionLevel: mixed
enableGlobalCache: false
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.3.1.cjs
```

.prettierrc.yml
```yml
plugins:
  - prettier-plugin-java
  - "@prettier/plugin-xml"
```

**Comment by jtkiesel** [comment]
Are you sure this issue is unique to this plugin? I tried with the following setup and saw a similar error:

```sh
> yarn lint
[error] Cannot find package '@prettier/plugin-xml' imported from /**/noop.js
```

package.json
```json
{
  "scripts": {
    "lint": "prettier --write src"
  },
  "devDependencies": {
    "@prettier/plugin-xml": "3.4.1",
    "prettier": "3.3.3"
  },
  "packageManager": "yarn@4.3.1"
}
```

yarnrc.yml
```yml
yarnPath: .yarn/releases/yarn-4.3.1.cjs
```

.prettierrc.yml
```yml
plugins:
  - "@prettier/plugin-xml"
```

After a bit of Googling, I found https://github.com/prettier/prettier/issues/15667#issuecomment-1827931416, which seems to be the current way of getting Prettier plugins to work with Yarn Plug'n'Play. A `.prettierrc.js` like the following seems to resolve the issue for both this plugin and the XML plugin:

```js
module.exports = {
  plugins: [
    require.resolve("@prettier/plugin-xml"),
    require.resolve("prettier-plugin-java"),
  ],
};
```

Can you try the above approach and let me know if it works for you?

**Comment by leaumar** [comment]
I guess it isn't just this plugin then. We'll try that, thank you. We don't really understand this issue anymore, because the results seem inconsistent between different projects, the same and different plugins, and between running via ide and cli.

**Comment by leaumar** [comment]
We're having trouble reproducing the issue now, all our formatting seems to just work this week, even without the different confg. I'm gonna close this, sorry for the noise and thanks for the config fix.
