### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startLine')

### ISSUE THREAD

**Issue by jameshearttech** [jhipster/prettier-java#685]
I'm getting a [type error](https://github.com/user-attachments/files/17233089/prettier.txt) formatting 1 particular file. Any ideas?

**Comment by jtkiesel** [comment]
Can you provide the file that you experience this error with?

**Comment by jameshearttech** [comment]
I probably cannot share it. It's from a private repository for work. I spent some time trying to figure out what is causing the error on my own, but this file is 4.5k lines so going through it by hand to look at every comment takes some time.

**Comment by jameshearttech** [comment]
I confirmed I cannot share the file. How can I tell where in the file the exception occurred?

**Comment by jameshearttech** [comment]
I set a breakpoint where the exception occurred in prettier and found the problem, but idk what is causing it.
