### ISSUE TITLE
Doesn't handle text blocks correctly

### ISSUE THREAD

**Issue by spieczkafollett** [jhipster/prettier-java#691]
**Prettier-Java 0.5.1**

```sh
# Options (if any):
<configuration>
  <tabWidth>4</tabWidth>
  <useTabs>true</useTabs>
</configuration>
```

**Input:**

```java
String textBlock = """
  {
     "kind": "%s",
  }
""".formatted(kind);
```

**Output:**

```java
[ERROR] Error: Sad sad panda, parsing errors detected in line: 208, column: 30!
[ERROR] Expecting --> ';' <-- but found --> '"
[ERROR]             {
[ERROR]              "' <--!
```

**Expected behavior:**
Should handle text blocks

**Comment by jtkiesel** [comment]
Support for text blocks was added in prettier-plugin-java [1.0.0](https://github.com/jhipster/prettier-java/releases/tag/v1.0.0). I'd recommend upgrading your version of prettier-plugin-java to the latest version, 2.6.4, if possible.
