### ISSUE TITLE
Checkstyle - WhitespaceAround: '{' is not preceded with whitespace

### ISSUE THREAD

**Issue by leinierperez** [jhipster/prettier-java#694]
Im using:
```
"prettier": "^3.3.3",
"prettier-plugin-java": "^2.6.4"
```

But still having this issue: https://github.com/jhipster/prettier-java/issues/686
Saw it was merged, so not sure whats going on. https://github.com/jhipster/prettier-java/pull/689

**Comment by jtkiesel** [comment]
#689 was merged on October 10th, while [2.6.4](https://github.com/jhipster/prettier-java/releases/tag/prettier-plugin-java%402.6.4) (the latest version, as you pointed out) was released on July 11th. The fix in #689 will be included in the next release.

**Comment by leinierperez** [comment]
> #689 was merged on October 10th, while [2.6.4](https://github.com/jhipster/prettier-java/releases/tag/prettier-plugin-java%402.6.4) (the latest version, as you pointed out) was released on July 11th. The fix in #689 will be included in the next release.

Oh i see, thanks. Is there a planned release date or is there a way i can build it myself?

**Comment by DanielFran** [comment]
@leinierperez new version available: https://www.npmjs.com/package/prettier-plugin-java/v/2.6.5
