### ISSUE TITLE
Upgrade to latest/fixed version of chevrotain-java

### ISSUE THREAD

**Issue by stil4m** [jhipster/prettier-java#82]
The latest version of prettier-java depends version `^0.0.13` java chevrotain-java. This breaks Java parsing for me ([see](https://github.com/thorbenvh8/chevrotain-java/issues/23): the syntax mentioned  in the issue is supported in `chevrotain-java@0.0.19`).

When I install the `prettier-java` dependency following the readme (`yarn add --dev --exact prettier prettier-plugin-java`), `chevrotain-java@0.0.13` will show up in my `node_modules`.

Should this package depend on a specific version of the `chevrotain-java` lib? And or not, how to ensure the latest version of the Java parser is used?

**Comment by bd82** [comment]
Hello @stil4m The repository is now mono-repo to avoid these kinds of problems.

I think it would be best to use [lerna fixed mode](https://github.com/lerna/lerna#fixedlocked-mode-default) initially so both packages will have the same version.

At a later time once things become more stable we can consider re-separating.
