### ISSUE TITLE
Convert from yarn to npm

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#93]
@jdubois wrote:

> Migrate from Yarn to NPM (as all other JHipster projects use NPM)

This is possible, but yarn has better support for mono repos.

- https://yarnpkg.com/lang/en/docs/workspaces/
- https://github.com/lerna/lerna/pull/899

I will create a PR for that and put @jdubois as a reviewer.

**Comment by deepu105** [comment]
I'm ok with this using Yarn since it has better support for monorepo

**Comment by bd82** [comment]
I will stay with Yarn because it supports workspaces (monorepos) better.
