### ISSUE TITLE
Modify License to Apache 2.0

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#94]
This will also resolve #79 

Note that lerna will take care of adding the license files to the individual packages.
https://github.com/lerna/lerna/pull/1465

So it is only needed at the root and of course the reference to a MIT license needs to be modified
in the package.json file**s**.

**Comment by jdubois** [comment]
Closing as this has been done in #120 (thanks @bd82 !)

**Comment by jdubois** [comment]
I have copied it from JHipster in https://github.com/jhipster/prettier-java/commit/16f57b356b7154c44eff30e487645e048ab939a6

Please note I have left myself as the contact point in case of trouble: one of my goal is to find someone else, who would be "neutral". I have asked several persons yet, but no success yet :-(
