### ISSUE TITLE
java-parser npm package name is already taken

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#98]
The original package name was "chevrotain-java" which is really bad.
* The name "chevrotain" itself is bad as it is too long... 😭 

A short descriptive name such as "java-parser" is best for discoverability.
However that name is already taken by an abandoned project.
* https://www.npmjs.com/package/java-parser

Should we try to obtain that package name?
* https://www.npmjs.com/policies/disputes

Or should we avoid the hassle and find an alternative name?
Anyone has any ideas for a better name?

**Comment by sparty02** [comment]
You could also consider creating a scope on npm, which is like a namespace.... like "jhipster".  In that case you could have a package name like @jhipster/java-parser

**Comment by bd82** [comment]
You could also consider creating a scope on npm, which is like a namespace.... like "jhipster". In that case you could have a package name like @jhipster/java-parser

Thanks @sparty02 I thought of this, but then I saw prettier plugin lookup mechneisim does not support
custom npm scopes. So it may be strange to have a scope for the java-parser package and no scope for the prettier-plugin-java package.

See: https://github.com/prettier/prettier/blob/master/docs/plugins.md#using-plugins

**Comment by bd82** [comment]
> Maybe try to put it in the @prettier scope?

Could work, but that what if they don't want a java-parser package "polluting" their scope?
Also it means somebody else will manage our permissions to such a scope (it already exists).
So maybe its best to keep prettier-java **independent** so we won't have to rely on anyone else for dev-ops/authorization issues.

**Comment by bd82** [comment]
https://github.com/sindresorhus/npm-name#readme

**Comment by jdubois** [comment]
We can try to get java-parser from NPM.
The name is awesome and the NPM team handling this is incredibly good, so it's definitely worth a try. I'll do it right now.

**Comment by jdubois** [comment]
Oups sorry, the process is first to ask the current owner - I'm with my phone so I can't run the npm command to get his email, @bd82 can you do it?

**Comment by deepu105** [comment]
what about `java-ast-parser` ?

**Comment by bd82** [comment]
>  @bd82 can you do it?

Email sent, cced both @jdubois @deepu105  and npm support.

**Comment by bd82** [comment]
> what about java-ast-parser ?

Yeah this is a fair option, other options:

- java-parser-js (if its not disallowed)
- java-to-ast-parser (a tiny bit too long, but descriptive)
- parse-java (```require("parse-java").parse)```

It could take 4 weeks+ to get the "java-parser" package name. but if that is our intent
I guess we should invest too much time in picking a temporary name and just use one that works for now.

**Comment by bd82** [comment]
I am in contact with @mazko the author of the "old" java-parser package regarding obtaining rights to package name.

In the meanwhile I changed the name (temp) to "java-parser-js" I hope that is not too similar and won't conflict with npm naming rules.

**Comment by bd82** [comment]
Allright, @jdubois You have owner privileges for the java-parser

>npm owner ls java-parser
jdubois <julien.dubois@...>
mazko <o.mazko@...>

**Comment by murdos** [comment]
Awesome! Thanks @bd82 !

**Comment by bd82** [comment]
Thank @mazko for resolving this so quickly 😄

**Comment by jdubois** [comment]
Oh yes thank you so much @mazko !!

**Comment by iamandrewluca** [comment]
Under what name we can find this package right now on npmjs?  
I want to use java parser as a dependency.

**Comment by murdos** [comment]
> 
> The new java-parser may not output an AST at all.

Would it be difficult to create AST in java-parser or in a new module?
Beyond prettier-java, having an AST parser would be very useful for jhipster modules and blueprints.

**Comment by bd82** [comment]
> Would it be difficult to create AST?

It won't be hard, it would just require a-lot of (simple) source code to implement,
For example see the current CST -> AST visitor (3,800 Lines)
- https://github.com/jhipster/prettier-java/blob/master/packages/java-parser/src/visitor.js
That is why I am **trying** to tackle the prettier scenario **without** requiring an AST.

>  in java-parser or in a new module?

The CST structure is **automagically** derived from the grammar structure 
That could make it difficult to develop the AST creation separately from the parser itself
by that problem can be mitigated by adding another package to this **mono-repo**
This could also be mitigated by a feature to generate a TypeScript API for the derived CST structure.
- https://github.com/SAP/chevrotain/issues/851

> Beyond prettier-java, having an AST parser would be very useful for jhipster modules and blueprints.

**Could you elaborate on that?**

**Comment by murdos** [comment]
Thanks for the detailed answer. 

> 
> **Could you elaborate on that?**

Sure. The use case for jhipster blueprint or module is to update/alter existing java files generated by jhipster-generator. As recommended by [Yeoman](https://yeoman.io/authoring/file-system.html), the perfect solution for that would be to use AST.
Currently you either have to deal with some complex regexp (that could break if source template is updated), or worse, copy jhipster template and integrate it inside your blueprint. 
In this latter case, if you don't manually merge changes made upstream in generator-jhipster, you don't benefit from new features and fixes.

What I would like to do for example is a jhispter module that integrates Lombok in the generated application, and for each entity would:
- remote all getter and setter methods
- remove equals and hashcode methodes
- add Lombok annotations: `@Getter`, `@Setter`, `@EqualsAndHashcode`

**Comment by bd82** [comment]
Alright I understand the scenario now.

Note that the scenario described is fairly complex, because it is not enough to modify the AST
you would also have to translate the AST changes to **incremental** text changes and those text changes would have side effects that could affect each other.
- For example deleting lines 10-12 would change the target offset of a change in line 15.
  - Assuming you know all the needed changes in advance and there is no offsets overlap between changes this can be resolved by performing the "largest offset" changes first (e.g first do the change in line 15, and only then in line 12)

Using an AST to model these changes is the correct approach, however if your use cases are simple like
one described above it may be possible to implement those directly on the CST too.

I am assuming the same limitations as in the prettier case apply on using JVM code here, basically that you need this code to run as **native JavaScript**. Because if not I would recommand
looking into Eclipse JDT or Jetbrains Java IDE support as these already implemented a refactoring framework.

**Comment by bd82** [comment]
@iamandrewluca see: https://www.npmjs.com/package/java-parser

This is the first alpha version with only a single API (parse).
APIs that will allow to crate CST visitors will be added in the (near?) future.
